
//
// This file was automatically generated by a deno script in:
// deno-scripts/opcode-gen.ts
//
// This file exists soley to be included into the interpreter 
// file so the switch statement isn't log as hell
// 
  
    case OP_NOP:
      break;
    case OP_MOV:
      m_registers[args[1]] = m_registers[args[0]];
      break;
    case OP_LOADCONST8:
      m_registers[args[0]] = READ_U8ARG(1);
      break;
    case OP_LOADCONST16:
      m_registers[args[0]] = READ_U16ARG(1);
      break;
    case OP_LOADCONST32:
      m_registers[args[0]] = READ_U32ARG(1);
      break;
    case OP_LOADCONST64:
      m_registers[args[0]] = READ_U64ARG(1);
      break;
    case OP_SREAD8:
      m_registers[args[0]] = READ_U8(stack, READ_U8ARG(1));
      break;
    case OP_SREAD16:
      m_registers[args[0]] = READ_U16(stack, READ_U16ARG(1));
      break;
    case OP_SREAD32:
      m_registers[args[0]] = READ_U32(stack, READ_U32ARG(1));
      break;
    case OP_SREAD64:
      m_registers[args[0]] = READ_U64(stack, READ_U64ARG(1));
      break;
    case OP_SWRITE8:
      WRITE_U8(stack, READ_U64ARG(1), m_registers[args[0]]);
      break;
    case OP_SWRITE16:
      WRITE_U16(stack, READ_U64ARG(1), m_registers[args[0]]);
      break;
    case OP_SWRITE32:
      WRITE_U32(stack, READ_U64ARG(1), m_registers[args[0]]);
      break;
    case OP_SWRITE64:
      WRITE_U64(stack, READ_U64ARG(1), m_registers[args[0]]);
      break;
    case OP_STORECONST8:
      WRITE_U8(stack, READ_U64ARG(0), READ_U8ARG(4));
      break;
    case OP_STORECONST16:
      WRITE_U16(stack, READ_U64ARG(0), READ_U16ARG(4));
      break;
    case OP_STORECONST32:
      WRITE_U32(stack, READ_U64ARG(0), READ_U32ARG(4));
      break;
    case OP_STORECONST64:
      WRITE_U64(stack, READ_U64ARG(0), READ_U64ARG(4));
      break;
    case OP_GREAD8:
      m_registers[args[0]] = READ_U8(global, READ_U8ARG(1));
      break;
    case OP_GREAD16:
      m_registers[args[0]] = READ_U16(global, READ_U16ARG(1));
      break;
    case OP_GREAD32:
      m_registers[args[0]] = READ_U32(global, READ_U32ARG(1));
      break;
    case OP_GREAD64:
      m_registers[args[0]] = READ_U64(global, READ_U64ARG(1));
      break;
    case OP_GWRITE8:
      WRITE_U8(global, READ_U64ARG(1), m_registers[args[0]]);
      break;
    case OP_GWRITE16:
      WRITE_U16(global, READ_U64ARG(1), m_registers[args[0]]);
      break;
    case OP_GWRITE32:
      WRITE_U32(global, READ_U64ARG(1), m_registers[args[0]]);
      break;
    case OP_GWRITE64:
      WRITE_U64(global, READ_U64ARG(1), m_registers[args[0]]);
      break;
    case OP_GSTORECONST8:
      WRITE_U8(global, READ_U64ARG(0), READ_U8ARG(4));
      break;
    case OP_GSTORECONST16:
      WRITE_U16(global, READ_U64ARG(0), READ_U16ARG(4));
      break;
    case OP_GSTORECONST32:
      WRITE_U32(global, READ_U64ARG(0), READ_U32ARG(4));
      break;
    case OP_GSTORECONST64:
      WRITE_U64(global, READ_U64ARG(0), READ_U64ARG(4));
      break;
    case OP_GETSTACKPTR:
      m_registers[args[0]] = reinterpret_cast<uint64>(stack);
      break;
    case OP_READOBJ8:
      m_registers[args[1]] = *reinterpret_cast<uint8*>(m_registers[args[0]] + READ_U32ARG(2) + REFCOUNT_PREFIX_SIZE);
      break;
    case OP_READOBJ16:
      m_registers[args[1]] = *reinterpret_cast<uint16*>(m_registers[args[0]] + READ_U32ARG(2) + REFCOUNT_PREFIX_SIZE);
      break;
    case OP_READOBJ32:
      m_registers[args[1]] = *reinterpret_cast<uint32*>(m_registers[args[0]] + READ_U32ARG(2) + REFCOUNT_PREFIX_SIZE);
      break;
    case OP_READOBJ64:
      m_registers[args[1]] = *reinterpret_cast<uint64*>(m_registers[args[0]] + READ_U32ARG(2) + REFCOUNT_PREFIX_SIZE);
      break;
    case OP_WRITEOBJ8:
      *reinterpret_cast<uint8*>(m_registers[args[0]] + READ_U32ARG(2) + REFCOUNT_PREFIX_SIZE) = REG_AS(args[0], uint8);
      break;
    case OP_WRITEOBJ16:
      *reinterpret_cast<uint16*>(m_registers[args[0]] + READ_U32ARG(2) + REFCOUNT_PREFIX_SIZE) = REG_AS(args[0], uint16);
      break;
    case OP_WRITEOBJ32:
      *reinterpret_cast<uint32*>(m_registers[args[0]] + READ_U32ARG(2) + REFCOUNT_PREFIX_SIZE) = REG_AS(args[0], uint32);
      break;
    case OP_WRITEOBJ64:
      *reinterpret_cast<uint64*>(m_registers[args[0]] + READ_U32ARG(2) + REFCOUNT_PREFIX_SIZE) = REG_AS(args[0], uint64);
      break;
    case OP_I8TU8:
      REG_AS(args[1], uint8) = static_cast<uint8>(REG_AS(args[0], int8));
      break;
    case OP_I8TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], int8));
      break;
    case OP_I8TU16:
      REG_AS(args[1], uint16) = static_cast<uint16>(REG_AS(args[0], int8));
      break;
    case OP_I8TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], int8));
      break;
    case OP_I8TU32:
      REG_AS(args[1], uint32) = static_cast<uint32>(REG_AS(args[0], int8));
      break;
    case OP_I8TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], int8));
      break;
    case OP_I8TU64:
      REG_AS(args[1], uint64) = static_cast<uint64>(REG_AS(args[0], int8));
      break;
    case OP_I8TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], int8));
      break;
    case OP_I8TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], int8));
      break;
    case OP_U8TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], uint8));
      break;
    case OP_U8TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], uint8));
      break;
    case OP_U8TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], uint8));
      break;
    case OP_U8TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], uint8));
      break;
    case OP_U8TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], uint8));
      break;
    case OP_U8TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], uint8));
      break;
    case OP_I16TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], int16));
      break;
    case OP_I16TU8:
      REG_AS(args[1], uint8) = static_cast<uint8>(REG_AS(args[0], int16));
      break;
    case OP_I16TU16:
      REG_AS(args[1], uint16) = static_cast<uint16>(REG_AS(args[0], int16));
      break;
    case OP_I16TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], int16));
      break;
    case OP_I16TU32:
      REG_AS(args[1], uint32) = static_cast<uint32>(REG_AS(args[0], int16));
      break;
    case OP_I16TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], int16));
      break;
    case OP_I16TU64:
      REG_AS(args[1], uint64) = static_cast<uint64>(REG_AS(args[0], int16));
      break;
    case OP_I16TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], int16));
      break;
    case OP_I16TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], int16));
      break;
    case OP_U16TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], uint16));
      break;
    case OP_U16TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], uint16));
      break;
    case OP_U16TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], uint16));
      break;
    case OP_U16TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], uint16));
      break;
    case OP_U16TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], uint16));
      break;
    case OP_U16TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], uint16));
      break;
    case OP_I32TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], int32));
      break;
    case OP_I32TU8:
      REG_AS(args[1], uint8) = static_cast<uint8>(REG_AS(args[0], int32));
      break;
    case OP_I32TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], int32));
      break;
    case OP_I32TU16:
      REG_AS(args[1], uint16) = static_cast<uint16>(REG_AS(args[0], int32));
      break;
    case OP_I32TU32:
      REG_AS(args[1], uint32) = static_cast<uint32>(REG_AS(args[0], int32));
      break;
    case OP_I32TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], int32));
      break;
    case OP_I32TU64:
      REG_AS(args[1], uint64) = static_cast<uint64>(REG_AS(args[0], int32));
      break;
    case OP_I32TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], int32));
      break;
    case OP_I32TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], int32));
      break;
    case OP_U32TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], uint32));
      break;
    case OP_U32TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], uint32));
      break;
    case OP_U32TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], uint32));
      break;
    case OP_U32TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], uint32));
      break;
    case OP_U32TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], uint32));
      break;
    case OP_U32TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], uint32));
      break;
    case OP_I64TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], int64));
      break;
    case OP_I64TU8:
      REG_AS(args[1], uint8) = static_cast<uint8>(REG_AS(args[0], int64));
      break;
    case OP_I64TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], int64));
      break;
    case OP_I64TU16:
      REG_AS(args[1], uint16) = static_cast<uint16>(REG_AS(args[0], int64));
      break;
    case OP_I64TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], int64));
      break;
    case OP_I64TU32:
      REG_AS(args[1], uint32) = static_cast<uint32>(REG_AS(args[0], int64));
      break;
    case OP_I64TU64:
      REG_AS(args[1], uint64) = static_cast<uint64>(REG_AS(args[0], int64));
      break;
    case OP_I64TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], int64));
      break;
    case OP_I64TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], int64));
      break;
    case OP_U64TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], uint64));
      break;
    case OP_U64TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], uint64));
      break;
    case OP_U64TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], uint64));
      break;
    case OP_U64TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], uint64));
      break;
    case OP_U64TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], uint64));
      break;
    case OP_U64TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], uint64));
      break;
    case OP_F32TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], float32));
      break;
    case OP_F32TU8:
      REG_AS(args[1], uint8) = static_cast<uint8>(REG_AS(args[0], float32));
      break;
    case OP_F32TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], float32));
      break;
    case OP_F32TU16:
      REG_AS(args[1], uint16) = static_cast<uint16>(REG_AS(args[0], float32));
      break;
    case OP_F32TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], float32));
      break;
    case OP_F32TU32:
      REG_AS(args[1], uint32) = static_cast<uint32>(REG_AS(args[0], float32));
      break;
    case OP_F32TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], float32));
      break;
    case OP_F32TU64:
      REG_AS(args[1], uint64) = static_cast<uint64>(REG_AS(args[0], float32));
      break;
    case OP_F32TF64:
      REG_AS(args[1], float64) = static_cast<float64>(REG_AS(args[0], float32));
      break;
    case OP_F64TI8:
      REG_AS(args[1], int8) = static_cast<int8>(REG_AS(args[0], float64));
      break;
    case OP_F64TU8:
      REG_AS(args[1], uint8) = static_cast<uint8>(REG_AS(args[0], float64));
      break;
    case OP_F64TI16:
      REG_AS(args[1], int16) = static_cast<int16>(REG_AS(args[0], float64));
      break;
    case OP_F64TU16:
      REG_AS(args[1], uint16) = static_cast<uint16>(REG_AS(args[0], float64));
      break;
    case OP_F64TI32:
      REG_AS(args[1], int32) = static_cast<int32>(REG_AS(args[0], float64));
      break;
    case OP_F64TU32:
      REG_AS(args[1], uint32) = static_cast<uint32>(REG_AS(args[0], float64));
      break;
    case OP_F64TI64:
      REG_AS(args[1], int64) = static_cast<int64>(REG_AS(args[0], float64));
      break;
    case OP_F64TU64:
      REG_AS(args[1], uint64) = static_cast<uint64>(REG_AS(args[0], float64));
      break;
    case OP_F64TF32:
      REG_AS(args[1], float32) = static_cast<float32>(REG_AS(args[0], float64));
      break;
    case OP_BNEGATE:
      m_registers[args[1]] = ~m_registers[args[0]];
      break;
    case OP_LNEGATE:
      m_registers[args[1]] = m_registers[args[0]] ? 0 : 1;
      break;
    case OP_NEGI8:
      REG_AS(args[1], int8) = -REG_AS(args[0], int8);
      break;
    case OP_NEGU8:
      REG_AS(args[1], int8) = -REG_AS(args[0], int8);
      break;
    case OP_NEGI16:
      REG_AS(args[1], int16) = -REG_AS(args[0], int16);
      break;
    case OP_NEGU16:
      REG_AS(args[1], int16) = -REG_AS(args[0], int16);
      break;
    case OP_NEGI32:
      REG_AS(args[1], int32) = -REG_AS(args[0], int32);
      break;
    case OP_NEGU32:
      REG_AS(args[1], int32) = -REG_AS(args[0], int32);
      break;
    case OP_NEGI64:
      REG_AS(args[1], int64) = -REG_AS(args[0], int64);
      break;
    case OP_NEGU64:
      REG_AS(args[1], int64) = -REG_AS(args[0], int64);
      break;
    case OP_NEGF32:
      REG_AS(args[1], float32) = -REG_AS(args[0], float32);
      break;
    case OP_NEGF64:
      REG_AS(args[1], float64) = -REG_AS(args[0], float64);
      break;
    case OP_INCI8:
      REG_AS(args[1], int8) = REG_AS(args[0], int8) + 1;
      break;
    case OP_INCU8:
      REG_AS(args[1], uint8) = REG_AS(args[0], uint8) + 1;
      break;
    case OP_INCI16:
      REG_AS(args[1], int16) = REG_AS(args[0], int16) + 1;
      break;
    case OP_INCU16:
      REG_AS(args[1], uint16) = REG_AS(args[0], uint16) + 1;
      break;
    case OP_INCI32:
      REG_AS(args[1], int32) = REG_AS(args[0], int32) + 1;
      break;
    case OP_INCU32:
      REG_AS(args[1], uint32) = REG_AS(args[0], uint32) + 1;
      break;
    case OP_INCI64:
      REG_AS(args[1], int64) = REG_AS(args[0], int64) + 1;
      break;
    case OP_INCU64:
      REG_AS(args[1], uint64) = REG_AS(args[0], uint64) + 1;
      break;
    case OP_INCF32:
      REG_AS(args[1], float32) = REG_AS(args[0], float32) + 1;
      break;
    case OP_INCF64:
      REG_AS(args[1], float64) = REG_AS(args[0], float64) + 1;
      break;
    case OP_DECI8:
      REG_AS(args[1], int8) = REG_AS(args[0], int8) - 1;
      break;
    case OP_DECU8:
      REG_AS(args[1], uint8) = REG_AS(args[0], uint8) - 1;
      break;
    case OP_DECI16:
      REG_AS(args[1], int16) = REG_AS(args[0], int16) - 1;
      break;
    case OP_DECU16:
      REG_AS(args[1], uint16) = REG_AS(args[0], uint16) - 1;
      break;
    case OP_DECI32:
      REG_AS(args[1], int32) = REG_AS(args[0], int32) - 1;
      break;
    case OP_DECU32:
      REG_AS(args[1], uint32) = REG_AS(args[0], uint32) - 1;
      break;
    case OP_DECI64:
      REG_AS(args[1], int64) = REG_AS(args[0], int64) - 1;
      break;
    case OP_DECU64:
      REG_AS(args[1], uint64) = REG_AS(args[0], uint64) - 1;
      break;
    case OP_DECF32:
      REG_AS(args[1], float32) = REG_AS(args[0], float32) - 1;
      break;
    case OP_DECF64:
      REG_AS(args[1], float64) = REG_AS(args[0], float64) - 1;
      break;
    case OP_LSHIFT:
      m_registers[args[2]] = m_registers[args[0]] << m_registers[args[1]];
      break;
    case OP_RSHIFT:
      m_registers[args[2]] = m_registers[args[0]] >> m_registers[args[1]];
      break;
    case OP_BAND:
      m_registers[args[2]] = m_registers[args[0]] & m_registers[args[1]];
      break;
    case OP_LAND:
      m_registers[args[2]] = m_registers[args[0]] && m_registers[args[1]];
      break;
    case OP_BOR:
      m_registers[args[2]] = m_registers[args[0]] | m_registers[args[1]];
      break;
    case OP_LOR:
      m_registers[args[2]] = m_registers[args[0]] || m_registers[args[1]];
      break;
    case OP_BXOR:
      m_registers[args[2]] = m_registers[args[0]] ^ m_registers[args[1]];
      break;
    case OP_LXOR:
      m_registers[args[2]] = !m_registers[args[0]] != !m_registers[args[1]];
      break;
    case OP_ADDI8:
      REG_AS(args[2], int8) = REG_AS(args[0], int8) + REG_AS(args[1], int8);
      break;
    case OP_ADDU8:
      REG_AS(args[2], uint8) = REG_AS(args[0], uint8) + REG_AS(args[1], uint8);
      break;
    case OP_ADDI16:
      REG_AS(args[2], int16) = REG_AS(args[0], int16) + REG_AS(args[1], int16);
      break;
    case OP_ADDU16:
      REG_AS(args[2], uint16) = REG_AS(args[0], uint16) + REG_AS(args[1], uint16);
      break;
    case OP_ADDI32:
      REG_AS(args[2], int32) = REG_AS(args[0], int32) + REG_AS(args[1], int32);
      break;
    case OP_ADDU32:
      REG_AS(args[2], uint32) = REG_AS(args[0], uint32) + REG_AS(args[1], uint32);
      break;
    case OP_ADDI64:
      REG_AS(args[2], int64) = REG_AS(args[0], int64) + REG_AS(args[1], int64);
      break;
    case OP_ADDU64:
      REG_AS(args[2], uint64) = REG_AS(args[0], uint64) + REG_AS(args[1], uint64);
      break;
    case OP_ADDF32:
      REG_AS(args[2], float32) = REG_AS(args[0], float32) + REG_AS(args[1], float32);
      break;
    case OP_ADDF64:
      REG_AS(args[2], float64) = REG_AS(args[0], float64) + REG_AS(args[1], float64);
      break;
    case OP_SUBI8:
      REG_AS(args[2], int8) = REG_AS(args[0], int8) - REG_AS(args[1], int8);
      break;
    case OP_SUBU8:
      REG_AS(args[2], uint8) = REG_AS(args[0], uint8) - REG_AS(args[1], uint8);
      break;
    case OP_SUBI16:
      REG_AS(args[2], int16) = REG_AS(args[0], int16) - REG_AS(args[1], int16);
      break;
    case OP_SUBU16:
      REG_AS(args[2], uint16) = REG_AS(args[0], uint16) - REG_AS(args[1], uint16);
      break;
    case OP_SUBI32:
      REG_AS(args[2], int32) = REG_AS(args[0], int32) - REG_AS(args[1], int32);
      break;
    case OP_SUBU32:
      REG_AS(args[2], uint32) = REG_AS(args[0], uint32) - REG_AS(args[1], uint32);
      break;
    case OP_SUBI64:
      REG_AS(args[2], int64) = REG_AS(args[0], int64) - REG_AS(args[1], int64);
      break;
    case OP_SUBU64:
      REG_AS(args[2], uint64) = REG_AS(args[0], uint64) - REG_AS(args[1], uint64);
      break;
    case OP_SUBF32:
      REG_AS(args[2], float32) = REG_AS(args[0], float32) - REG_AS(args[1], float32);
      break;
    case OP_SUBF64:
      REG_AS(args[2], float64) = REG_AS(args[0], float64) - REG_AS(args[1], float64);
      break;
    case OP_DIVI8:
      REG_AS(args[2], int8) = REG_AS(args[0], int8) / REG_AS(args[1], int8);
      break;
    case OP_DIVU8:
      REG_AS(args[2], uint8) = REG_AS(args[0], uint8) / REG_AS(args[1], uint8);
      break;
    case OP_DIVI16:
      REG_AS(args[2], int16) = REG_AS(args[0], int16) / REG_AS(args[1], int16);
      break;
    case OP_DIVU16:
      REG_AS(args[2], uint16) = REG_AS(args[0], uint16) / REG_AS(args[1], uint16);
      break;
    case OP_DIVI32:
      REG_AS(args[2], int32) = REG_AS(args[0], int32) / REG_AS(args[1], int32);
      break;
    case OP_DIVU32:
      REG_AS(args[2], uint32) = REG_AS(args[0], uint32) / REG_AS(args[1], uint32);
      break;
    case OP_DIVI64:
      REG_AS(args[2], int64) = REG_AS(args[0], int64) / REG_AS(args[1], int64);
      break;
    case OP_DIVU64:
      REG_AS(args[2], uint64) = REG_AS(args[0], uint64) / REG_AS(args[1], uint64);
      break;
    case OP_DIVF32:
      REG_AS(args[2], float32) = REG_AS(args[0], float32) / REG_AS(args[1], float32);
      break;
    case OP_DIVF64:
      REG_AS(args[2], float64) = REG_AS(args[0], float64) / REG_AS(args[1], float64);
      break;
    case OP_MULI8:
      REG_AS(args[2], int8) = REG_AS(args[0], int8) * REG_AS(args[1], int8);
      break;
    case OP_MULU8:
      REG_AS(args[2], uint8) = REG_AS(args[0], uint8) * REG_AS(args[1], uint8);
      break;
    case OP_MULI16:
      REG_AS(args[2], int16) = REG_AS(args[0], int16) * REG_AS(args[1], int16);
      break;
    case OP_MULU16:
      REG_AS(args[2], uint16) = REG_AS(args[0], uint16) * REG_AS(args[1], uint16);
      break;
    case OP_MULI32:
      REG_AS(args[2], int32) = REG_AS(args[0], int32) * REG_AS(args[1], int32);
      break;
    case OP_MULU32:
      REG_AS(args[2], uint32) = REG_AS(args[0], uint32) * REG_AS(args[1], uint32);
      break;
    case OP_MULI64:
      REG_AS(args[2], int64) = REG_AS(args[0], int64) * REG_AS(args[1], int64);
      break;
    case OP_MULU64:
      REG_AS(args[2], uint64) = REG_AS(args[0], uint64) * REG_AS(args[1], uint64);
      break;
    case OP_MULF32:
      REG_AS(args[2], float32) = REG_AS(args[0], float32) * REG_AS(args[1], float32);
      break;
    case OP_MULF64:
      REG_AS(args[2], float64) = REG_AS(args[0], float64) * REG_AS(args[1], float64);
      break;
    case OP_MODI8:
      REG_AS(args[2], int8) = REG_AS(args[0], int8) % REG_AS(args[1], int8);
      break;
    case OP_MODU8:
      REG_AS(args[2], uint8) = REG_AS(args[0], uint8) % REG_AS(args[1], uint8);
      break;
    case OP_MODI16:
      REG_AS(args[2], int16) = REG_AS(args[0], int16) % REG_AS(args[1], int16);
      break;
    case OP_MODU16:
      REG_AS(args[2], uint16) = REG_AS(args[0], uint16) % REG_AS(args[1], uint16);
      break;
    case OP_MODI32:
      REG_AS(args[2], int32) = REG_AS(args[0], int32) % REG_AS(args[1], int32);
      break;
    case OP_MODU32:
      REG_AS(args[2], uint32) = REG_AS(args[0], uint32) % REG_AS(args[1], uint32);
      break;
    case OP_MODI64:
      REG_AS(args[2], int64) = REG_AS(args[0], int64) % REG_AS(args[1], int64);
      break;
    case OP_MODU64:
      REG_AS(args[2], uint64) = REG_AS(args[0], uint64) % REG_AS(args[1], uint64);
      break;
    case OP_MODF32:
      REG_AS(args[2], float32) = fmod(REG_AS(args[0], float32), REG_AS(args[1], float32));
      break;
    case OP_MODF64:
      REG_AS(args[2], float64) = fmod(REG_AS(args[0], float64), REG_AS(args[1], float64));
      break;
    case OP_POWI8:
      REG_AS(args[2], int8) = std::pow(REG_AS(args[0], int8), REG_AS(args[1], int8));
      break;
    case OP_POWU8:
      REG_AS(args[2], uint8) = std::pow(REG_AS(args[0], uint8), REG_AS(args[1], uint8));
      break;
    case OP_POWI16:
      REG_AS(args[2], int16) = std::pow(REG_AS(args[0], int16), REG_AS(args[1], int16));
      break;
    case OP_POWU16:
      REG_AS(args[2], uint16) = std::pow(REG_AS(args[0], uint16), REG_AS(args[1], uint16));
      break;
    case OP_POWI32:
      REG_AS(args[2], int32) = std::pow(REG_AS(args[0], int32), REG_AS(args[1], int32));
      break;
    case OP_POWU32:
      REG_AS(args[2], uint32) = std::pow(REG_AS(args[0], uint32), REG_AS(args[1], uint32));
      break;
    case OP_POWI64:
      REG_AS(args[2], int64) = std::pow(REG_AS(args[0], int64), REG_AS(args[1], int64));
      break;
    case OP_POWU64:
      REG_AS(args[2], uint64) = std::pow(REG_AS(args[0], uint64), REG_AS(args[1], uint64));
      break;
    case OP_POWF32:
      REG_AS(args[2], float32) = std::pow(REG_AS(args[0], float32), REG_AS(args[1], float32));
      break;
    case OP_POWF64:
      REG_AS(args[2], float64) = std::pow(REG_AS(args[0], float64), REG_AS(args[1], float64));
      break;
    case OP_EQ8:
      m_registers[args[2]] = m_registers[args[0]] == m_registers[args[1]];
      break;
    case OP_EQ16:
      m_registers[args[2]] = m_registers[args[0]] == m_registers[args[1]];
      break;
    case OP_EQ32:
      m_registers[args[2]] = m_registers[args[0]] == m_registers[args[1]];
      break;
    case OP_EQ64:
      m_registers[args[2]] = m_registers[args[0]] == m_registers[args[1]];
      break;
    case OP_NEQ8:
      m_registers[args[2]] = m_registers[args[0]] != m_registers[args[1]];
      break;
    case OP_NEQ16:
      m_registers[args[2]] = m_registers[args[0]] != m_registers[args[1]];
      break;
    case OP_NEQ32:
      m_registers[args[2]] = m_registers[args[0]] != m_registers[args[1]];
      break;
    case OP_NEQ64:
      m_registers[args[2]] = m_registers[args[0]] != m_registers[args[1]];
      break;
    case OP_GTI8:
      m_registers[args[2]] = REG_AS(args[0], int8) > REG_AS(args[1], int8);
      break;
    case OP_GTU8:
      m_registers[args[2]] = REG_AS(args[0], uint8) > REG_AS(args[1], uint8);
      break;
    case OP_GTI16:
      m_registers[args[2]] = REG_AS(args[0], int16) > REG_AS(args[1], int16);
      break;
    case OP_GTU16:
      m_registers[args[2]] = REG_AS(args[0], uint16) > REG_AS(args[1], uint16);
      break;
    case OP_GTI32:
      m_registers[args[2]] = REG_AS(args[0], int32) > REG_AS(args[1], int32);
      break;
    case OP_GTU32:
      m_registers[args[2]] = REG_AS(args[0], uint32) > REG_AS(args[1], uint32);
      break;
    case OP_GTI64:
      m_registers[args[2]] = REG_AS(args[0], int64) > REG_AS(args[1], int64);
      break;
    case OP_GTU64:
      m_registers[args[2]] = REG_AS(args[0], uint64) > REG_AS(args[1], uint64);
      break;
    case OP_GTF32:
      m_registers[args[2]] = REG_AS(args[0], float32) > REG_AS(args[1], float32);
      break;
    case OP_GTF64:
      m_registers[args[2]] = REG_AS(args[0], float64) > REG_AS(args[1], float64);
      break;
    case OP_GTEI8:
      m_registers[args[2]] = REG_AS(args[0], int8) >= REG_AS(args[1], int8);
      break;
    case OP_GTEU8:
      m_registers[args[2]] = REG_AS(args[0], uint8) >= REG_AS(args[1], uint8);
      break;
    case OP_GTEI16:
      m_registers[args[2]] = REG_AS(args[0], int16) >= REG_AS(args[1], int16);
      break;
    case OP_GTEU16:
      m_registers[args[2]] = REG_AS(args[0], uint16) >= REG_AS(args[1], uint16);
      break;
    case OP_GTEI32:
      m_registers[args[2]] = REG_AS(args[0], int32) >= REG_AS(args[1], int32);
      break;
    case OP_GTEU32:
      m_registers[args[2]] = REG_AS(args[0], uint32) >= REG_AS(args[1], uint32);
      break;
    case OP_GTEI64:
      m_registers[args[2]] = REG_AS(args[0], int64) >= REG_AS(args[1], int64);
      break;
    case OP_GTEU64:
      m_registers[args[2]] = REG_AS(args[0], uint64) >= REG_AS(args[1], uint64);
      break;
    case OP_GTEF32:
      m_registers[args[2]] = REG_AS(args[0], float32) >= REG_AS(args[1], float32);
      break;
    case OP_GTEF64:
      m_registers[args[2]] = REG_AS(args[0], float64) >= REG_AS(args[1], float64);
      break;
    case OP_LTI8:
      m_registers[args[2]] = REG_AS(args[0], int8) < REG_AS(args[1], int8);
      break;
    case OP_LTU8:
      m_registers[args[2]] = REG_AS(args[0], uint8) < REG_AS(args[1], uint8);
      break;
    case OP_LTI16:
      m_registers[args[2]] = REG_AS(args[0], int16) < REG_AS(args[1], int16);
      break;
    case OP_LTU16:
      m_registers[args[2]] = REG_AS(args[0], uint16) < REG_AS(args[1], uint16);
      break;
    case OP_LTI32:
      m_registers[args[2]] = REG_AS(args[0], int32) < REG_AS(args[1], int32);
      break;
    case OP_LTU32:
      m_registers[args[2]] = REG_AS(args[0], uint32) < REG_AS(args[1], uint32);
      break;
    case OP_LTI64:
      m_registers[args[2]] = REG_AS(args[0], int64) < REG_AS(args[1], int64);
      break;
    case OP_LTU64:
      m_registers[args[2]] = REG_AS(args[0], uint64) < REG_AS(args[1], uint64);
      break;
    case OP_LTF32:
      m_registers[args[2]] = REG_AS(args[0], float32) < REG_AS(args[1], float32);
      break;
    case OP_LTF64:
      m_registers[args[2]] = REG_AS(args[0], float64) < REG_AS(args[1], float64);
      break;
    case OP_LTEI8:
      m_registers[args[2]] = REG_AS(args[0], int8) <= REG_AS(args[1], int8);
      break;
    case OP_LTEU8:
      m_registers[args[2]] = REG_AS(args[0], uint8) <= REG_AS(args[1], uint8);
      break;
    case OP_LTEI16:
      m_registers[args[2]] = REG_AS(args[0], int16) <= REG_AS(args[1], int16);
      break;
    case OP_LTEU16:
      m_registers[args[2]] = REG_AS(args[0], uint16) <= REG_AS(args[1], uint16);
      break;
    case OP_LTEI32:
      m_registers[args[2]] = REG_AS(args[0], int32) <= REG_AS(args[1], int32);
      break;
    case OP_LTEU32:
      m_registers[args[2]] = REG_AS(args[0], uint32) <= REG_AS(args[1], uint32);
      break;
    case OP_LTEI64:
      m_registers[args[2]] = REG_AS(args[0], int64) <= REG_AS(args[1], int64);
      break;
    case OP_LTEU64:
      m_registers[args[2]] = REG_AS(args[0], uint64) <= REG_AS(args[1], uint64);
      break;
    case OP_LTEF32:
      m_registers[args[2]] = REG_AS(args[0], float32) <= REG_AS(args[1], float32);
      break;
    case OP_LTEF64:
      m_registers[args[2]] = REG_AS(args[0], float64) <= REG_AS(args[1], float64);
      break;