#ifndef OPCODE_PRINTER_H
#define OPCODE_PRINTER_H

#include <cstdio>

#include "opcodes.h"

//
// This file was automatically generated by a deno script in:
// deno-scripts/opcode-gen.ts
//

void printInstructionToString(uint8* buf, FILE* out);

#endif // OPCODE_PRINTER_H