#ifndef QUICKSCRIPT_OPCODES_H
#define QUICKSCRIPT_OPCODES_H

#include "../common.h"

#define LENGTH_OPCODE 2
#define LENGTH_ARGS 14
#define LENGTH_INSTRUCTION 16

//
// This file was automatically generated by a deno script in:
// ./deno-code-gen
//
// Section numbers that you see here are references to this:
// https://juliewoolie.com/blog/quickscript
// I wrote a bunch of the specification and planning there
//

// General Purpose OP Codes
#define OP_NOP             0x0000
#define OP_PUSHLINE        0x0001
#define OP_RET             0x0002
#define OP_JMP             0x0003
#define OP_JMPI0           0x0004
#define OP_JMPN0           0x0005
#define OP_ASSERT          0x0006
#define OP_MOV             0x0007
#define OP_LOADCONST8      0x0008
#define OP_LOADCONST16     0x0009
#define OP_LOADCONST32     0x000A
#define OP_LOADCONST64     0x000B
#define OP_LOADCONSTSTR    0x000C

// Stack Memory OP Codes
#define OP_SREAD8          0x000D
#define OP_SREAD16         0x000E
#define OP_SREAD32         0x000F
#define OP_SREAD64         0x0010
#define OP_SWRITE8         0x0011
#define OP_SWRITE16        0x0012
#define OP_SWRITE32        0x0013
#define OP_SWRITE64        0x0014
#define OP_STORECONST8     0x0015
#define OP_STORECONST16    0x0016
#define OP_STORECONST32    0x0017
#define OP_STORECONST64    0x0018

// Global Memory OP Codes
#define OP_GREAD8          0x0019
#define OP_GREAD16         0x001A
#define OP_GREAD32         0x001B
#define OP_GREAD64         0x001C
#define OP_GWRITE8         0x001D
#define OP_GWRITE16        0x001E
#define OP_GWRITE32        0x001F
#define OP_GWRITE64        0x0020
#define OP_GSTORECONST8    0x0021
#define OP_GSTORECONST16   0x0022
#define OP_GSTORECONST32   0x0023
#define OP_GSTORECONST64   0x0024

// Closure OP Codes
#define OP_GETSTACKPTR     0x0025
#define OP_CREAD8          0x0026
#define OP_CREAD16         0x0027
#define OP_CREAD32         0x0028
#define OP_CREAD64         0x0029
#define OP_CWRITE8         0x002A
#define OP_CWRITE16        0x002B
#define OP_CWRITE32        0x002C
#define OP_CWRITE64        0x002D

// Heap Memory OP Codes
#define OP_OBJALLOC        0x002E
#define OP_ARRAYALLOC      0x002F
#define OP_INCREFC         0x0030
#define OP_DECREFC         0x0031
#define OP_READOBJ8        0x0032
#define OP_READOBJ16       0x0033
#define OP_READOBJ32       0x0034
#define OP_READOBJ64       0x0035
#define OP_WRITEOBJ8       0x0036
#define OP_WRITEOBJ16      0x0037
#define OP_WRITEOBJ32      0x0038
#define OP_WRITEOBJ64      0x0039
#define OP_READIDX8        0x003A
#define OP_READIDX16       0x003B
#define OP_READIDX32       0x003C
#define OP_READIDX64       0x003D
#define OP_WRITEIDX8       0x003E
#define OP_WRITEIDX16      0x003F
#define OP_WRITEIDX32      0x0040
#define OP_WRITEIDX64      0x0041
#define OP_ARRLEN          0x0042

// Function Call Instructions
#define OP_LFUNCLOOKUP     0x0043
#define OP_NFUNCLOOKUP     0x0044
#define OP_INVOKE          0x0045

// Foreign Symbol OP Codes
#define OP_FREAD           0x0046
#define OP_FWRITE          0x0047

// Conversion Instructions
#define OP_I8TU8           0x0048
#define OP_I8TI16          0x0049
#define OP_I8TU16          0x004A
#define OP_I8TI32          0x004B
#define OP_I8TU32          0x004C
#define OP_I8TI64          0x004D
#define OP_I8TU64          0x004E
#define OP_I8TF32          0x004F
#define OP_I8TF64          0x0050
#define OP_U8TI8           0x0051
#define OP_U8TI16          0x0052
#define OP_U8TI32          0x0053
#define OP_U8TI64          0x0054
#define OP_U8TF32          0x0055
#define OP_U8TF64          0x0056
#define OP_I16TI8          0x0057
#define OP_I16TU8          0x0058
#define OP_I16TU16         0x0059
#define OP_I16TI32         0x005A
#define OP_I16TU32         0x005B
#define OP_I16TI64         0x005C
#define OP_I16TU64         0x005D
#define OP_I16TF32         0x005E
#define OP_I16TF64         0x005F
#define OP_U16TI8          0x0060
#define OP_U16TI16         0x0061
#define OP_U16TI32         0x0062
#define OP_U16TI64         0x0063
#define OP_U16TF32         0x0064
#define OP_U16TF64         0x0065
#define OP_I32TI8          0x0066
#define OP_I32TU8          0x0067
#define OP_I32TI16         0x0068
#define OP_I32TU16         0x0069
#define OP_I32TU32         0x006A
#define OP_I32TI64         0x006B
#define OP_I32TU64         0x006C
#define OP_I32TF32         0x006D
#define OP_I32TF64         0x006E
#define OP_U32TI8          0x006F
#define OP_U32TI16         0x0070
#define OP_U32TI32         0x0071
#define OP_U32TI64         0x0072
#define OP_U32TF32         0x0073
#define OP_U32TF64         0x0074
#define OP_I64TI8          0x0075
#define OP_I64TU8          0x0076
#define OP_I64TI16         0x0077
#define OP_I64TU16         0x0078
#define OP_I64TI32         0x0079
#define OP_I64TU32         0x007A
#define OP_I64TU64         0x007B
#define OP_I64TF32         0x007C
#define OP_I64TF64         0x007D
#define OP_U64TI8          0x007E
#define OP_U64TI16         0x007F
#define OP_U64TI32         0x0080
#define OP_U64TI64         0x0081
#define OP_U64TF32         0x0082
#define OP_U64TF64         0x0083
#define OP_F32TI8          0x0084
#define OP_F32TU8          0x0085
#define OP_F32TI16         0x0086
#define OP_F32TU16         0x0087
#define OP_F32TI32         0x0088
#define OP_F32TU32         0x0089
#define OP_F32TI64         0x008A
#define OP_F32TU64         0x008B
#define OP_F32TF64         0x008C
#define OP_F64TI8          0x008D
#define OP_F64TU8          0x008E
#define OP_F64TI16         0x008F
#define OP_F64TU16         0x0090
#define OP_F64TI32         0x0091
#define OP_F64TU32         0x0092
#define OP_F64TI64         0x0093
#define OP_F64TU64         0x0094
#define OP_F64TF32         0x0095

// Unary Operations
#define OP_BNEGATE         0x0096
#define OP_LNEGATE         0x0097
#define OP_NEGI8           0x0098
#define OP_NEGU8           0x0099
#define OP_NEGI16          0x009A
#define OP_NEGU16          0x009B
#define OP_NEGI32          0x009C
#define OP_NEGU32          0x009D
#define OP_NEGI64          0x009E
#define OP_NEGU64          0x009F
#define OP_NEGF32          0x00A0
#define OP_NEGF64          0x00A1
#define OP_INCI8           0x00A2
#define OP_INCU8           0x00A3
#define OP_INCI16          0x00A4
#define OP_INCU16          0x00A5
#define OP_INCI32          0x00A6
#define OP_INCU32          0x00A7
#define OP_INCI64          0x00A8
#define OP_INCU64          0x00A9
#define OP_INCF32          0x00AA
#define OP_INCF64          0x00AB
#define OP_DECI8           0x00AC
#define OP_DECU8           0x00AD
#define OP_DECI16          0x00AE
#define OP_DECU16          0x00AF
#define OP_DECI32          0x00B0
#define OP_DECU32          0x00B1
#define OP_DECI64          0x00B2
#define OP_DECU64          0x00B3
#define OP_DECF32          0x00B4
#define OP_DECF64          0x00B5

// Integer-only Binary Operations
#define OP_LSHIFT          0x00B6
#define OP_RSHIFT          0x00B7

// Boolean-only Binary Operations
#define OP_BAND            0x00B8
#define OP_LAND            0x00B9
#define OP_BOR             0x00BA
#define OP_LOR             0x00BB
#define OP_BXOR            0x00BC
#define OP_LXOR            0x00BD

// General Number Binary Operations
#define OP_ADDI8           0x00BE
#define OP_ADDU8           0x00BF
#define OP_ADDI16          0x00C0
#define OP_ADDU16          0x00C1
#define OP_ADDI32          0x00C2
#define OP_ADDU32          0x00C3
#define OP_ADDI64          0x00C4
#define OP_ADDU64          0x00C5
#define OP_ADDF32          0x00C6
#define OP_ADDF64          0x00C7
#define OP_SUBI8           0x00C8
#define OP_SUBU8           0x00C9
#define OP_SUBI16          0x00CA
#define OP_SUBU16          0x00CB
#define OP_SUBI32          0x00CC
#define OP_SUBU32          0x00CD
#define OP_SUBI64          0x00CE
#define OP_SUBU64          0x00CF
#define OP_SUBF32          0x00D0
#define OP_SUBF64          0x00D1
#define OP_DIVI8           0x00D2
#define OP_DIVU8           0x00D3
#define OP_DIVI16          0x00D4
#define OP_DIVU16          0x00D5
#define OP_DIVI32          0x00D6
#define OP_DIVU32          0x00D7
#define OP_DIVI64          0x00D8
#define OP_DIVU64          0x00D9
#define OP_DIVF32          0x00DA
#define OP_DIVF64          0x00DB
#define OP_MULI8           0x00DC
#define OP_MULU8           0x00DD
#define OP_MULI16          0x00DE
#define OP_MULU16          0x00DF
#define OP_MULI32          0x00E0
#define OP_MULU32          0x00E1
#define OP_MULI64          0x00E2
#define OP_MULU64          0x00E3
#define OP_MULF32          0x00E4
#define OP_MULF64          0x00E5
#define OP_MODI8           0x00E6
#define OP_MODU8           0x00E7
#define OP_MODI16          0x00E8
#define OP_MODU16          0x00E9
#define OP_MODI32          0x00EA
#define OP_MODU32          0x00EB
#define OP_MODI64          0x00EC
#define OP_MODU64          0x00ED
#define OP_MODF32          0x00EE
#define OP_MODF64          0x00EF
#define OP_POWI8           0x00F0
#define OP_POWU8           0x00F1
#define OP_POWI16          0x00F2
#define OP_POWU16          0x00F3
#define OP_POWI32          0x00F4
#define OP_POWU32          0x00F5
#define OP_POWI64          0x00F6
#define OP_POWU64          0x00F7
#define OP_POWF32          0x00F8
#define OP_POWF64          0x00F9

// Comparison Operations
#define OP_EQ8             0x00FA
#define OP_EQ16            0x00FB
#define OP_EQ32            0x00FC
#define OP_EQ64            0x00FD
#define OP_EQARR           0x00FE
#define OP_EQSTRUCT        0x00FF
#define OP_NEQ8            0x0100
#define OP_NEQ16           0x0101
#define OP_NEQ32           0x0102
#define OP_NEQ64           0x0103
#define OP_NEQARR          0x0104
#define OP_NEQSTRUCT       0x0105
#define OP_GTI8            0x0106
#define OP_GTU8            0x0107
#define OP_GTI16           0x0108
#define OP_GTU16           0x0109
#define OP_GTI32           0x010A
#define OP_GTU32           0x010B
#define OP_GTI64           0x010C
#define OP_GTU64           0x010D
#define OP_GTF32           0x010E
#define OP_GTF64           0x010F
#define OP_GTARR           0x0110
#define OP_GTEI8           0x0111
#define OP_GTEU8           0x0112
#define OP_GTEI16          0x0113
#define OP_GTEU16          0x0114
#define OP_GTEI32          0x0115
#define OP_GTEU32          0x0116
#define OP_GTEI64          0x0117
#define OP_GTEU64          0x0118
#define OP_GTEF32          0x0119
#define OP_GTEF64          0x011A
#define OP_GTEARR          0x011B
#define OP_LTI8            0x011C
#define OP_LTU8            0x011D
#define OP_LTI16           0x011E
#define OP_LTU16           0x011F
#define OP_LTI32           0x0120
#define OP_LTU32           0x0121
#define OP_LTI64           0x0122
#define OP_LTU64           0x0123
#define OP_LTF32           0x0124
#define OP_LTF64           0x0125
#define OP_LTARR           0x0126
#define OP_LTEI8           0x0127
#define OP_LTEU8           0x0128
#define OP_LTEI16          0x0129
#define OP_LTEU16          0x012A
#define OP_LTEI32          0x012B
#define OP_LTEU32          0x012C
#define OP_LTEI64          0x012D
#define OP_LTEU64          0x012E
#define OP_LTEF32          0x012F
#define OP_LTEF64          0x0130
#define OP_LTEARR          0x0131

// String/Array Operations
#define OP_STRCONCAT       0x0132
#define OP_STRREP8         0x0133
#define OP_STRREP16        0x0134
#define OP_STRREP32        0x0135
#define OP_STRREP64        0x0136

#define LAST_OPCODE OP_STRREP64
#define OPCODE_COUNT 311

typedef uint16 opcode;

conststring opcode_name(opcode code);

uint8 getInstructionLength(opcode code);

#endif //QUICKSCRIPT_OPCODES_H