#include "opcode_printer.h"

//
// This file was automatically generated by a deno script in:
// ./deno-code-gen
//

static conststring getRegistryName(const uint8 r) {
  switch(r) {
    case 0: return "rvr";
    case 1: return "icr";
    case 2: return "r02";
    case 3: return "r03";
    case 4: return "r04";
    case 5: return "r05";
    case 6: return "r06";
    case 7: return "r07";
    case 8: return "r08";
    case 9: return "r09";
    case 10: return "r10";
    case 11: return "r11";
    case 12: return "r12";
    case 13: return "r13";
    case 14: return "r14";
    case 15: return "r15";
    case 16: return "r16";
    case 17: return "r17";
    case 18: return "r18";
    case 19: return "r19";
    case 20: return "r20";
    case 21: return "r21";
    case 22: return "r22";
    case 23: return "r23";
    case 24: return "r24";
    case 25: return "r25";
    case 26: return "r26";
    case 27: return "r27";
    case 28: return "r28";
    case 29: return "r29";
    case 30: return "r30";
    case 31: return "r31";
    case 32: return "r32";
    case 33: return "r33";
    case 34: return "r34";
    case 35: return "r35";
    case 36: return "r36";
    case 37: return "r37";
    case 38: return "r38";
    case 39: return "r39";
    case 40: return "r40";
    case 41: return "r41";
    case 42: return "r42";
    case 43: return "r43";
    case 44: return "r44";
    case 45: return "r45";
    case 46: return "r46";
    case 47: return "r47";
    case 48: return "r48";
    case 49: return "r49";
    case 50: return "r50";
    case 51: return "r51";
    case 52: return "r52";
    case 53: return "r53";
    case 54: return "r54";
    case 55: return "r55";
    case 56: return "r56";
    case 57: return "r57";
    case 58: return "r58";
    case 59: return "r59";
    case 60: return "r60";
    case 61: return "r61";
    case 62: return "r62";
    case 63: return "r63";
    default: return "INVALID_REGISTRY";
  }
}

void printTypeIndex(FILE* out, const typeindex idx) {
  if (idx < LAST_RESERVED_TYPE_INDEX) {
    fprintf(out, "%s", nativeTypeIndexName(idx));
    return;
  }
  fprintf(out, "%llu", idx);
}

void printInstructionToString(uint8* buf, FILE* out, uint8* strPool) {
  const opcode code = *reinterpret_cast<opcode*>(buf);
  fprintf(out, "%-13s", opcode_name(code));
  
  switch (code) {
    case OP_NOP:
    case OP_RET:
      break;
    case OP_PUSHLINE:
      fprintf(out, " /*lineno*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 2));
      break;
    case OP_JMP:
      fprintf(out, " /*to*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 2));
      break;
    case OP_JMPI0:
    case OP_JMPN0:
      fprintf(out, " /*to*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 2));
      fprintf(out, " /*condition*/");
      fprintf(out, " %s", getRegistryName(*(buf + 6)));
      break;
    case OP_ASSERT:
      fprintf(out, " /*condition*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*message*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      break;
    case OP_MOV:
      fprintf(out, " /*from*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*to*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      break;
    case OP_LOADCONST8:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*val*/");
      fprintf(out, " %d", *(buf + 3));
      break;
    case OP_LOADCONST16:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*val*/");
      fprintf(out, " %d", *reinterpret_cast<uint16*>(buf + 3));
      break;
    case OP_LOADCONST32:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*val*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 3));
      break;
    case OP_LOADCONST64:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*val*/");
      fprintf(out, " %llu", *reinterpret_cast<uint64*>(buf + 3));
      break;
    case OP_LOADCONSTSTR:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*straddr*/");
      fprintf(out, " STRINGS[off=%llu] /* %.*s */", *reinterpret_cast<uint64*>(buf + 3), *reinterpret_cast<uint32*>(strPool + *reinterpret_cast<uint64*>(buf + 3)), reinterpret_cast<char*>(strPool + sizeof(uint32) + *reinterpret_cast<uint64*>(buf + 3)));
      break;
    case OP_SREAD8:
    case OP_SREAD16:
    case OP_SREAD32:
    case OP_SREAD64:
    case OP_GREAD8:
    case OP_GREAD16:
    case OP_GREAD32:
    case OP_GREAD64:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*offset*/");
      fprintf(out, " %llu", *reinterpret_cast<uint64*>(buf + 3));
      break;
    case OP_SWRITE8:
    case OP_SWRITE16:
    case OP_SWRITE32:
    case OP_SWRITE64:
    case OP_GWRITE8:
    case OP_GWRITE16:
    case OP_GWRITE32:
    case OP_GWRITE64:
      fprintf(out, " /*val*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*offset*/");
      fprintf(out, " %llu", *reinterpret_cast<uint64*>(buf + 3));
      break;
    case OP_STORECONST8:
    case OP_GSTORECONST8:
      fprintf(out, " /*offset*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 2));
      fprintf(out, " /*value*/");
      fprintf(out, " %d", *(buf + 6));
      break;
    case OP_STORECONST16:
    case OP_GSTORECONST16:
      fprintf(out, " /*offset*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 2));
      fprintf(out, " /*value*/");
      fprintf(out, " %d", *reinterpret_cast<uint16*>(buf + 6));
      break;
    case OP_STORECONST32:
    case OP_GSTORECONST32:
      fprintf(out, " /*offset*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 2));
      fprintf(out, " /*value*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 6));
      break;
    case OP_STORECONST64:
    case OP_GSTORECONST64:
      fprintf(out, " /*offset*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 2));
      fprintf(out, " /*value*/");
      fprintf(out, " %llu", *reinterpret_cast<uint64*>(buf + 6));
      break;
    case OP_GETSTACKPTR:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      break;
    case OP_CREAD8:
    case OP_CREAD16:
    case OP_CREAD32:
    case OP_CREAD64:
      fprintf(out, " /*closure*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*off*/");
      fprintf(out, " %llu", *reinterpret_cast<uint64*>(buf + 3));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 11)));
      break;
    case OP_CWRITE8:
    case OP_CWRITE16:
    case OP_CWRITE32:
    case OP_CWRITE64:
      fprintf(out, " /*closure*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*off*/");
      fprintf(out, " %llu", *reinterpret_cast<uint64*>(buf + 3));
      fprintf(out, " /*val*/");
      fprintf(out, " %s", getRegistryName(*(buf + 11)));
      break;
    case OP_OBJALLOC:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*typeindex*/");
      fprintf(out, " TYPES[");
      printTypeIndex(out, *reinterpret_cast<uint32*>(buf + 3));
      fprintf(out, "]");
      break;
    case OP_ARRAYALLOC:
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*count*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 3));
      fprintf(out, " /*typeindex*/");
      fprintf(out, " TYPES[");
      printTypeIndex(out, *reinterpret_cast<uint32*>(buf + 7));
      fprintf(out, "]");
      break;
    case OP_INCREFC:
    case OP_DECREFC:
      fprintf(out, " /*obj*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      break;
    case OP_READOBJ8:
    case OP_READOBJ16:
    case OP_READOBJ32:
    case OP_READOBJ64:
      fprintf(out, " /*obj*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      fprintf(out, " /*off*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 4));
      break;
    case OP_WRITEOBJ8:
    case OP_WRITEOBJ16:
    case OP_WRITEOBJ32:
    case OP_WRITEOBJ64:
      fprintf(out, " /*obj*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*val*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      fprintf(out, " /*off*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 4));
      break;
    case OP_READIDX8:
    case OP_READIDX16:
    case OP_READIDX32:
    case OP_READIDX64:
      fprintf(out, " /*obj*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      fprintf(out, " /*idx*/");
      fprintf(out, " %s", getRegistryName(*(buf + 4)));
      break;
    case OP_WRITEIDX8:
    case OP_WRITEIDX16:
    case OP_WRITEIDX32:
    case OP_WRITEIDX64:
      fprintf(out, " /*obj*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*val*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      fprintf(out, " /*idx*/");
      fprintf(out, " %s", getRegistryName(*(buf + 4)));
      break;
    case OP_ARRLEN:
      fprintf(out, " /*obj*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      break;
    case OP_LFUNCLOOKUP:
      fprintf(out, " /*index*/");
      fprintf(out, " %d", *reinterpret_cast<uint32*>(buf + 2));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 6)));
      break;
    case OP_NFUNCLOOKUP:
      fprintf(out, " /*typeindex*/");
      fprintf(out, " TYPES[");
      printTypeIndex(out, *reinterpret_cast<uint32*>(buf + 2));
      fprintf(out, "]");
      fprintf(out, " /*funcName*/");
      fprintf(out, " STRINGS[off=%llu] /* %.*s */", *reinterpret_cast<uint64*>(buf + 6), *reinterpret_cast<uint32*>(strPool + *reinterpret_cast<uint64*>(buf + 6)), reinterpret_cast<char*>(strPool + sizeof(uint32) + *reinterpret_cast<uint64*>(buf + 6)));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 14)));
      break;
    case OP_INVOKE:
      fprintf(out, " /*func*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      break;
    case OP_I8TU8:
    case OP_I8TI16:
    case OP_I8TU16:
    case OP_I8TI32:
    case OP_I8TU32:
    case OP_I8TI64:
    case OP_I8TU64:
    case OP_I8TF32:
    case OP_I8TF64:
    case OP_U8TI8:
    case OP_U8TI16:
    case OP_U8TI32:
    case OP_U8TI64:
    case OP_U8TF32:
    case OP_U8TF64:
    case OP_I16TI8:
    case OP_I16TU8:
    case OP_I16TU16:
    case OP_I16TI32:
    case OP_I16TU32:
    case OP_I16TI64:
    case OP_I16TU64:
    case OP_I16TF32:
    case OP_I16TF64:
    case OP_U16TI8:
    case OP_U16TI16:
    case OP_U16TI32:
    case OP_U16TI64:
    case OP_U16TF32:
    case OP_U16TF64:
    case OP_I32TI8:
    case OP_I32TU8:
    case OP_I32TI16:
    case OP_I32TU16:
    case OP_I32TU32:
    case OP_I32TI64:
    case OP_I32TU64:
    case OP_I32TF32:
    case OP_I32TF64:
    case OP_U32TI8:
    case OP_U32TI16:
    case OP_U32TI32:
    case OP_U32TI64:
    case OP_U32TF32:
    case OP_U32TF64:
    case OP_I64TI8:
    case OP_I64TU8:
    case OP_I64TI16:
    case OP_I64TU16:
    case OP_I64TI32:
    case OP_I64TU32:
    case OP_I64TU64:
    case OP_I64TF32:
    case OP_I64TF64:
    case OP_U64TI8:
    case OP_U64TI16:
    case OP_U64TI32:
    case OP_U64TI64:
    case OP_U64TF32:
    case OP_U64TF64:
    case OP_F32TI8:
    case OP_F32TU8:
    case OP_F32TI16:
    case OP_F32TU16:
    case OP_F32TI32:
    case OP_F32TU32:
    case OP_F32TI64:
    case OP_F32TU64:
    case OP_F32TF64:
    case OP_F64TI8:
    case OP_F64TU8:
    case OP_F64TI16:
    case OP_F64TU16:
    case OP_F64TI32:
    case OP_F64TU32:
    case OP_F64TI64:
    case OP_F64TU64:
    case OP_F64TF32:
    case OP_BNEGATE:
    case OP_LNEGATE:
    case OP_NEGI8:
    case OP_NEGU8:
    case OP_NEGI16:
    case OP_NEGU16:
    case OP_NEGI32:
    case OP_NEGU32:
    case OP_NEGI64:
    case OP_NEGU64:
    case OP_NEGF32:
    case OP_NEGF64:
    case OP_INCI8:
    case OP_INCU8:
    case OP_INCI16:
    case OP_INCU16:
    case OP_INCI32:
    case OP_INCU32:
    case OP_INCI64:
    case OP_INCU64:
    case OP_INCF32:
    case OP_INCF64:
    case OP_DECI8:
    case OP_DECU8:
    case OP_DECI16:
    case OP_DECU16:
    case OP_DECI32:
    case OP_DECU32:
    case OP_DECI64:
    case OP_DECU64:
    case OP_DECF32:
    case OP_DECF64:
      fprintf(out, " /*in*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      break;
    case OP_LSHIFT:
    case OP_RSHIFT:
    case OP_BAND:
    case OP_LAND:
    case OP_BOR:
    case OP_LOR:
    case OP_BXOR:
    case OP_LXOR:
    case OP_ADDI8:
    case OP_ADDU8:
    case OP_ADDI16:
    case OP_ADDU16:
    case OP_ADDI32:
    case OP_ADDU32:
    case OP_ADDI64:
    case OP_ADDU64:
    case OP_ADDF32:
    case OP_ADDF64:
    case OP_SUBI8:
    case OP_SUBU8:
    case OP_SUBI16:
    case OP_SUBU16:
    case OP_SUBI32:
    case OP_SUBU32:
    case OP_SUBI64:
    case OP_SUBU64:
    case OP_SUBF32:
    case OP_SUBF64:
    case OP_DIVI8:
    case OP_DIVU8:
    case OP_DIVI16:
    case OP_DIVU16:
    case OP_DIVI32:
    case OP_DIVU32:
    case OP_DIVI64:
    case OP_DIVU64:
    case OP_DIVF32:
    case OP_DIVF64:
    case OP_MULI8:
    case OP_MULU8:
    case OP_MULI16:
    case OP_MULU16:
    case OP_MULI32:
    case OP_MULU32:
    case OP_MULI64:
    case OP_MULU64:
    case OP_MULF32:
    case OP_MULF64:
    case OP_MODI8:
    case OP_MODU8:
    case OP_MODI16:
    case OP_MODU16:
    case OP_MODI32:
    case OP_MODU32:
    case OP_MODI64:
    case OP_MODU64:
    case OP_MODF32:
    case OP_MODF64:
    case OP_POWI8:
    case OP_POWU8:
    case OP_POWI16:
    case OP_POWU16:
    case OP_POWI32:
    case OP_POWU32:
    case OP_POWI64:
    case OP_POWU64:
    case OP_POWF32:
    case OP_POWF64:
    case OP_EQ8:
    case OP_EQ16:
    case OP_EQ32:
    case OP_EQ64:
    case OP_NEQ8:
    case OP_NEQ16:
    case OP_NEQ32:
    case OP_NEQ64:
    case OP_GTI8:
    case OP_GTU8:
    case OP_GTI16:
    case OP_GTU16:
    case OP_GTI32:
    case OP_GTU32:
    case OP_GTI64:
    case OP_GTU64:
    case OP_GTF32:
    case OP_GTF64:
    case OP_GTEI8:
    case OP_GTEU8:
    case OP_GTEI16:
    case OP_GTEU16:
    case OP_GTEI32:
    case OP_GTEU32:
    case OP_GTEI64:
    case OP_GTEU64:
    case OP_GTEF32:
    case OP_GTEF64:
    case OP_LTI8:
    case OP_LTU8:
    case OP_LTI16:
    case OP_LTU16:
    case OP_LTI32:
    case OP_LTU32:
    case OP_LTI64:
    case OP_LTU64:
    case OP_LTF32:
    case OP_LTF64:
    case OP_LTEI8:
    case OP_LTEU8:
    case OP_LTEI16:
    case OP_LTEU16:
    case OP_LTEI32:
    case OP_LTEU32:
    case OP_LTEI64:
    case OP_LTEU64:
    case OP_LTEF32:
    case OP_LTEF64:
    case OP_STRREP8:
    case OP_STRREP16:
    case OP_STRREP32:
    case OP_STRREP64:
      fprintf(out, " /*lhs*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*rhs*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 4)));
      break;
    case OP_EQARR:
    case OP_EQSTRUCT:
    case OP_NEQARR:
    case OP_NEQSTRUCT:
    case OP_GTARR:
    case OP_GTEARR:
    case OP_LTARR:
    case OP_LTEARR:
      fprintf(out, " /*lhs*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*rhs*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 4)));
      fprintf(out, " /*typeindex*/");
      fprintf(out, " TYPES[");
      printTypeIndex(out, *reinterpret_cast<uint32*>(buf + 5));
      fprintf(out, "]");
      break;
    case OP_STRCONCAT:
      fprintf(out, " /*lhs*/");
      fprintf(out, " %s", getRegistryName(*(buf + 2)));
      fprintf(out, " /*rhs*/");
      fprintf(out, " %s", getRegistryName(*(buf + 3)));
      fprintf(out, " /*typeindex*/");
      fprintf(out, " TYPES[");
      printTypeIndex(out, *reinterpret_cast<uint32*>(buf + 4));
      fprintf(out, "]");
      fprintf(out, " /*out*/");
      fprintf(out, " %s", getRegistryName(*(buf + 8)));
      break;
    default:
      break;
  }
}