#include "opcodes.h"

//
// This file was automatically generated by a deno script in:
// deno-scripts/opcode-gen.ts
//

conststring opcode_name(opcode code) {
  switch (code) {
    case OP_PUSHLINE: return "PUSHLINE";
    case OP_RET: return "RET";
    case OP_JMP: return "JMP";
    case OP_JMPI0: return "JMPI0";
    case OP_JMPN0: return "JMPN0";
    case OP_ASSERT: return "ASSERT";
    case OP_MOV: return "MOV";
    case OP_LOADCONST8: return "LOADCONST8";
    case OP_LOADCONST16: return "LOADCONST16";
    case OP_LOADCONST32: return "LOADCONST32";
    case OP_LOADCONST64: return "LOADCONST64";
    case OP_LOADCONSTSTR: return "LOADCONSTSTR";
    case OP_SREAD8: return "SREAD8";
    case OP_SREAD16: return "SREAD16";
    case OP_SREAD32: return "SREAD32";
    case OP_SREAD64: return "SREAD64";
    case OP_SWRITE8: return "SWRITE8";
    case OP_SWRITE16: return "SWRITE16";
    case OP_SWRITE32: return "SWRITE32";
    case OP_SWRITE64: return "SWRITE64";
    case OP_STORECONST8: return "STORECONST8";
    case OP_STORECONST16: return "STORECONST16";
    case OP_STORECONST32: return "STORECONST32";
    case OP_STORECONST64: return "STORECONST64";
    case OP_GREAD8: return "GREAD8";
    case OP_GREAD16: return "GREAD16";
    case OP_GREAD32: return "GREAD32";
    case OP_GREAD64: return "GREAD64";
    case OP_GWRITE8: return "GWRITE8";
    case OP_GWRITE16: return "GWRITE16";
    case OP_GWRITE32: return "GWRITE32";
    case OP_GWRITE64: return "GWRITE64";
    case OP_GSTORECONST8: return "GSTORECONST8";
    case OP_GSTORECONST16: return "GSTORECONST16";
    case OP_GSTORECONST32: return "GSTORECONST32";
    case OP_GSTORECONST64: return "GSTORECONST64";
    case OP_GETSTACKPTR: return "GETSTACKPTR";
    case OP_CREAD8: return "CREAD8";
    case OP_CREAD16: return "CREAD16";
    case OP_CREAD32: return "CREAD32";
    case OP_CREAD64: return "CREAD64";
    case OP_CWRITE8: return "CWRITE8";
    case OP_CWRITE16: return "CWRITE16";
    case OP_CWRITE32: return "CWRITE32";
    case OP_CWRITE64: return "CWRITE64";
    case OP_OBJALLOC: return "OBJALLOC";
    case OP_ARRAYALLOC: return "ARRAYALLOC";
    case OP_INCREFC: return "INCREFC";
    case OP_DECREFC: return "DECREFC";
    case OP_READOBJ8: return "READOBJ8";
    case OP_READOBJ16: return "READOBJ16";
    case OP_READOBJ32: return "READOBJ32";
    case OP_READOBJ64: return "READOBJ64";
    case OP_WRITEOBJ8: return "WRITEOBJ8";
    case OP_WRITEOBJ16: return "WRITEOBJ16";
    case OP_WRITEOBJ32: return "WRITEOBJ32";
    case OP_WRITEOBJ64: return "WRITEOBJ64";
    case OP_READIDX8: return "READIDX8";
    case OP_READIDX16: return "READIDX16";
    case OP_READIDX32: return "READIDX32";
    case OP_READIDX64: return "READIDX64";
    case OP_WRITEIDX8: return "WRITEIDX8";
    case OP_WRITEIDX16: return "WRITEIDX16";
    case OP_WRITEIDX32: return "WRITEIDX32";
    case OP_WRITEIDX64: return "WRITEIDX64";
    case OP_ARRLEN: return "ARRLEN";
    case OP_SETARGTYPE: return "SETARGTYPE";
    case OP_LFUNCLOOKUP: return "LFUNCLOOKUP";
    case OP_NFUNCLOOKUP: return "NFUNCLOOKUP";
    case OP_INVOKE: return "INVOKE";
    case OP_I8TU8: return "I8TU8";
    case OP_I8TI16: return "I8TI16";
    case OP_I8TU16: return "I8TU16";
    case OP_I8TI32: return "I8TI32";
    case OP_I8TU32: return "I8TU32";
    case OP_I8TI64: return "I8TI64";
    case OP_I8TU64: return "I8TU64";
    case OP_I8TF32: return "I8TF32";
    case OP_I8TF64: return "I8TF64";
    case OP_U8TI8: return "U8TI8";
    case OP_U8TI16: return "U8TI16";
    case OP_U8TI32: return "U8TI32";
    case OP_U8TI64: return "U8TI64";
    case OP_U8TF32: return "U8TF32";
    case OP_U8TF64: return "U8TF64";
    case OP_I16TI8: return "I16TI8";
    case OP_I16TU8: return "I16TU8";
    case OP_I16TU16: return "I16TU16";
    case OP_I16TI32: return "I16TI32";
    case OP_I16TU32: return "I16TU32";
    case OP_I16TI64: return "I16TI64";
    case OP_I16TU64: return "I16TU64";
    case OP_I16TF32: return "I16TF32";
    case OP_I16TF64: return "I16TF64";
    case OP_U16TI8: return "U16TI8";
    case OP_U16TI16: return "U16TI16";
    case OP_U16TI32: return "U16TI32";
    case OP_U16TI64: return "U16TI64";
    case OP_U16TF32: return "U16TF32";
    case OP_U16TF64: return "U16TF64";
    case OP_I32TI8: return "I32TI8";
    case OP_I32TU8: return "I32TU8";
    case OP_I32TI16: return "I32TI16";
    case OP_I32TU16: return "I32TU16";
    case OP_I32TU32: return "I32TU32";
    case OP_I32TI64: return "I32TI64";
    case OP_I32TU64: return "I32TU64";
    case OP_I32TF32: return "I32TF32";
    case OP_I32TF64: return "I32TF64";
    case OP_U32TI8: return "U32TI8";
    case OP_U32TI16: return "U32TI16";
    case OP_U32TI32: return "U32TI32";
    case OP_U32TI64: return "U32TI64";
    case OP_U32TF32: return "U32TF32";
    case OP_U32TF64: return "U32TF64";
    case OP_I64TI8: return "I64TI8";
    case OP_I64TU8: return "I64TU8";
    case OP_I64TI16: return "I64TI16";
    case OP_I64TU16: return "I64TU16";
    case OP_I64TI32: return "I64TI32";
    case OP_I64TU32: return "I64TU32";
    case OP_I64TU64: return "I64TU64";
    case OP_I64TF32: return "I64TF32";
    case OP_I64TF64: return "I64TF64";
    case OP_U64TI8: return "U64TI8";
    case OP_U64TI16: return "U64TI16";
    case OP_U64TI32: return "U64TI32";
    case OP_U64TI64: return "U64TI64";
    case OP_U64TF32: return "U64TF32";
    case OP_U64TF64: return "U64TF64";
    case OP_F32TI8: return "F32TI8";
    case OP_F32TU8: return "F32TU8";
    case OP_F32TI16: return "F32TI16";
    case OP_F32TU16: return "F32TU16";
    case OP_F32TI32: return "F32TI32";
    case OP_F32TU32: return "F32TU32";
    case OP_F32TI64: return "F32TI64";
    case OP_F32TU64: return "F32TU64";
    case OP_F32TF64: return "F32TF64";
    case OP_F64TI8: return "F64TI8";
    case OP_F64TU8: return "F64TU8";
    case OP_F64TI16: return "F64TI16";
    case OP_F64TU16: return "F64TU16";
    case OP_F64TI32: return "F64TI32";
    case OP_F64TU32: return "F64TU32";
    case OP_F64TI64: return "F64TI64";
    case OP_F64TU64: return "F64TU64";
    case OP_F64TF32: return "F64TF32";
    case OP_BNEGATE: return "BNEGATE";
    case OP_LNEGATE: return "LNEGATE";
    case OP_NEGI8: return "NEGI8";
    case OP_NEGU8: return "NEGU8";
    case OP_NEGI16: return "NEGI16";
    case OP_NEGU16: return "NEGU16";
    case OP_NEGI32: return "NEGI32";
    case OP_NEGU32: return "NEGU32";
    case OP_NEGI64: return "NEGI64";
    case OP_NEGU64: return "NEGU64";
    case OP_NEGF32: return "NEGF32";
    case OP_NEGF64: return "NEGF64";
    case OP_INCI8: return "INCI8";
    case OP_INCU8: return "INCU8";
    case OP_INCI16: return "INCI16";
    case OP_INCU16: return "INCU16";
    case OP_INCI32: return "INCI32";
    case OP_INCU32: return "INCU32";
    case OP_INCI64: return "INCI64";
    case OP_INCU64: return "INCU64";
    case OP_INCF32: return "INCF32";
    case OP_INCF64: return "INCF64";
    case OP_DECI8: return "DECI8";
    case OP_DECU8: return "DECU8";
    case OP_DECI16: return "DECI16";
    case OP_DECU16: return "DECU16";
    case OP_DECI32: return "DECI32";
    case OP_DECU32: return "DECU32";
    case OP_DECI64: return "DECI64";
    case OP_DECU64: return "DECU64";
    case OP_DECF32: return "DECF32";
    case OP_DECF64: return "DECF64";
    case OP_LSHIFT: return "LSHIFT";
    case OP_RSHIFT: return "RSHIFT";
    case OP_BAND: return "BAND";
    case OP_LAND: return "LAND";
    case OP_BOR: return "BOR";
    case OP_LOR: return "LOR";
    case OP_BXOR: return "BXOR";
    case OP_LXOR: return "LXOR";
    case OP_ADDI8: return "ADDI8";
    case OP_ADDU8: return "ADDU8";
    case OP_ADDI16: return "ADDI16";
    case OP_ADDU16: return "ADDU16";
    case OP_ADDI32: return "ADDI32";
    case OP_ADDU32: return "ADDU32";
    case OP_ADDI64: return "ADDI64";
    case OP_ADDU64: return "ADDU64";
    case OP_ADDF32: return "ADDF32";
    case OP_ADDF64: return "ADDF64";
    case OP_SUBI8: return "SUBI8";
    case OP_SUBU8: return "SUBU8";
    case OP_SUBI16: return "SUBI16";
    case OP_SUBU16: return "SUBU16";
    case OP_SUBI32: return "SUBI32";
    case OP_SUBU32: return "SUBU32";
    case OP_SUBI64: return "SUBI64";
    case OP_SUBU64: return "SUBU64";
    case OP_SUBF32: return "SUBF32";
    case OP_SUBF64: return "SUBF64";
    case OP_DIVI8: return "DIVI8";
    case OP_DIVU8: return "DIVU8";
    case OP_DIVI16: return "DIVI16";
    case OP_DIVU16: return "DIVU16";
    case OP_DIVI32: return "DIVI32";
    case OP_DIVU32: return "DIVU32";
    case OP_DIVI64: return "DIVI64";
    case OP_DIVU64: return "DIVU64";
    case OP_DIVF32: return "DIVF32";
    case OP_DIVF64: return "DIVF64";
    case OP_MULI8: return "MULI8";
    case OP_MULU8: return "MULU8";
    case OP_MULI16: return "MULI16";
    case OP_MULU16: return "MULU16";
    case OP_MULI32: return "MULI32";
    case OP_MULU32: return "MULU32";
    case OP_MULI64: return "MULI64";
    case OP_MULU64: return "MULU64";
    case OP_MULF32: return "MULF32";
    case OP_MULF64: return "MULF64";
    case OP_MODI8: return "MODI8";
    case OP_MODU8: return "MODU8";
    case OP_MODI16: return "MODI16";
    case OP_MODU16: return "MODU16";
    case OP_MODI32: return "MODI32";
    case OP_MODU32: return "MODU32";
    case OP_MODI64: return "MODI64";
    case OP_MODU64: return "MODU64";
    case OP_MODF32: return "MODF32";
    case OP_MODF64: return "MODF64";
    case OP_POWI8: return "POWI8";
    case OP_POWU8: return "POWU8";
    case OP_POWI16: return "POWI16";
    case OP_POWU16: return "POWU16";
    case OP_POWI32: return "POWI32";
    case OP_POWU32: return "POWU32";
    case OP_POWI64: return "POWI64";
    case OP_POWU64: return "POWU64";
    case OP_POWF32: return "POWF32";
    case OP_POWF64: return "POWF64";
    case OP_EQ8: return "EQ8";
    case OP_EQ16: return "EQ16";
    case OP_EQ32: return "EQ32";
    case OP_EQ64: return "EQ64";
    case OP_EQARR: return "EQARR";
    case OP_EQSTRUCT: return "EQSTRUCT";
    case OP_NEQ8: return "NEQ8";
    case OP_NEQ16: return "NEQ16";
    case OP_NEQ32: return "NEQ32";
    case OP_NEQ64: return "NEQ64";
    case OP_NEQARR: return "NEQARR";
    case OP_NEQSTRUCT: return "NEQSTRUCT";
    case OP_GTI8: return "GTI8";
    case OP_GTU8: return "GTU8";
    case OP_GTI16: return "GTI16";
    case OP_GTU16: return "GTU16";
    case OP_GTI32: return "GTI32";
    case OP_GTU32: return "GTU32";
    case OP_GTI64: return "GTI64";
    case OP_GTU64: return "GTU64";
    case OP_GTF32: return "GTF32";
    case OP_GTF64: return "GTF64";
    case OP_GTARR: return "GTARR";
    case OP_GTEI8: return "GTEI8";
    case OP_GTEU8: return "GTEU8";
    case OP_GTEI16: return "GTEI16";
    case OP_GTEU16: return "GTEU16";
    case OP_GTEI32: return "GTEI32";
    case OP_GTEU32: return "GTEU32";
    case OP_GTEI64: return "GTEI64";
    case OP_GTEU64: return "GTEU64";
    case OP_GTEF32: return "GTEF32";
    case OP_GTEF64: return "GTEF64";
    case OP_GTEARR: return "GTEARR";
    case OP_LTI8: return "LTI8";
    case OP_LTU8: return "LTU8";
    case OP_LTI16: return "LTI16";
    case OP_LTU16: return "LTU16";
    case OP_LTI32: return "LTI32";
    case OP_LTU32: return "LTU32";
    case OP_LTI64: return "LTI64";
    case OP_LTU64: return "LTU64";
    case OP_LTF32: return "LTF32";
    case OP_LTF64: return "LTF64";
    case OP_LTARR: return "LTARR";
    case OP_LTEI8: return "LTEI8";
    case OP_LTEU8: return "LTEU8";
    case OP_LTEI16: return "LTEI16";
    case OP_LTEU16: return "LTEU16";
    case OP_LTEI32: return "LTEI32";
    case OP_LTEU32: return "LTEU32";
    case OP_LTEI64: return "LTEI64";
    case OP_LTEU64: return "LTEU64";
    case OP_LTEF32: return "LTEF32";
    case OP_LTEF64: return "LTEF64";
    case OP_LTEARR: return "LTEARR";
    case OP_STRCONCAT: return "STRCONCAT";
    case OP_STRREP8: return "STRREP8";
    case OP_STRREP16: return "STRREP16";
    case OP_STRREP32: return "STRREP32";
    case OP_STRREP64: return "STRREP64";
    default: return "NOP";
  }
}

uint8 getInstructionLength(const opcode code) {
  switch (code) {
    case OP_NOP:
    case OP_RET:
      return LENGTH_OPCODE;
    case OP_GETSTACKPTR:
    case OP_INCREFC:
    case OP_DECREFC:
    case OP_INVOKE:
      return 1 + LENGTH_OPCODE;
    case OP_ASSERT:
    case OP_MOV:
    case OP_LOADCONST8:
    case OP_ARRLEN:
    case OP_I8TU8:
    case OP_I8TI16:
    case OP_I8TU16:
    case OP_I8TI32:
    case OP_I8TU32:
    case OP_I8TI64:
    case OP_I8TU64:
    case OP_I8TF32:
    case OP_I8TF64:
    case OP_U8TI8:
    case OP_U8TI16:
    case OP_U8TI32:
    case OP_U8TI64:
    case OP_U8TF32:
    case OP_U8TF64:
    case OP_I16TI8:
    case OP_I16TU8:
    case OP_I16TU16:
    case OP_I16TI32:
    case OP_I16TU32:
    case OP_I16TI64:
    case OP_I16TU64:
    case OP_I16TF32:
    case OP_I16TF64:
    case OP_U16TI8:
    case OP_U16TI16:
    case OP_U16TI32:
    case OP_U16TI64:
    case OP_U16TF32:
    case OP_U16TF64:
    case OP_I32TI8:
    case OP_I32TU8:
    case OP_I32TI16:
    case OP_I32TU16:
    case OP_I32TU32:
    case OP_I32TI64:
    case OP_I32TU64:
    case OP_I32TF32:
    case OP_I32TF64:
    case OP_U32TI8:
    case OP_U32TI16:
    case OP_U32TI32:
    case OP_U32TI64:
    case OP_U32TF32:
    case OP_U32TF64:
    case OP_I64TI8:
    case OP_I64TU8:
    case OP_I64TI16:
    case OP_I64TU16:
    case OP_I64TI32:
    case OP_I64TU32:
    case OP_I64TU64:
    case OP_I64TF32:
    case OP_I64TF64:
    case OP_U64TI8:
    case OP_U64TI16:
    case OP_U64TI32:
    case OP_U64TI64:
    case OP_U64TF32:
    case OP_U64TF64:
    case OP_F32TI8:
    case OP_F32TU8:
    case OP_F32TI16:
    case OP_F32TU16:
    case OP_F32TI32:
    case OP_F32TU32:
    case OP_F32TI64:
    case OP_F32TU64:
    case OP_F32TF64:
    case OP_F64TI8:
    case OP_F64TU8:
    case OP_F64TI16:
    case OP_F64TU16:
    case OP_F64TI32:
    case OP_F64TU32:
    case OP_F64TI64:
    case OP_F64TU64:
    case OP_F64TF32:
    case OP_BNEGATE:
    case OP_LNEGATE:
    case OP_NEGI8:
    case OP_NEGU8:
    case OP_NEGI16:
    case OP_NEGU16:
    case OP_NEGI32:
    case OP_NEGU32:
    case OP_NEGI64:
    case OP_NEGU64:
    case OP_NEGF32:
    case OP_NEGF64:
    case OP_INCI8:
    case OP_INCU8:
    case OP_INCI16:
    case OP_INCU16:
    case OP_INCI32:
    case OP_INCU32:
    case OP_INCI64:
    case OP_INCU64:
    case OP_INCF32:
    case OP_INCF64:
    case OP_DECI8:
    case OP_DECU8:
    case OP_DECI16:
    case OP_DECU16:
    case OP_DECI32:
    case OP_DECU32:
    case OP_DECI64:
    case OP_DECU64:
    case OP_DECF32:
    case OP_DECF64:
      return 2 + LENGTH_OPCODE;
    case OP_LOADCONST16:
    case OP_READIDX8:
    case OP_READIDX16:
    case OP_READIDX32:
    case OP_READIDX64:
    case OP_WRITEIDX8:
    case OP_WRITEIDX16:
    case OP_WRITEIDX32:
    case OP_WRITEIDX64:
    case OP_LSHIFT:
    case OP_RSHIFT:
    case OP_BAND:
    case OP_LAND:
    case OP_BOR:
    case OP_LOR:
    case OP_BXOR:
    case OP_LXOR:
    case OP_ADDI8:
    case OP_ADDU8:
    case OP_ADDI16:
    case OP_ADDU16:
    case OP_ADDI32:
    case OP_ADDU32:
    case OP_ADDI64:
    case OP_ADDU64:
    case OP_ADDF32:
    case OP_ADDF64:
    case OP_SUBI8:
    case OP_SUBU8:
    case OP_SUBI16:
    case OP_SUBU16:
    case OP_SUBI32:
    case OP_SUBU32:
    case OP_SUBI64:
    case OP_SUBU64:
    case OP_SUBF32:
    case OP_SUBF64:
    case OP_DIVI8:
    case OP_DIVU8:
    case OP_DIVI16:
    case OP_DIVU16:
    case OP_DIVI32:
    case OP_DIVU32:
    case OP_DIVI64:
    case OP_DIVU64:
    case OP_DIVF32:
    case OP_DIVF64:
    case OP_MULI8:
    case OP_MULU8:
    case OP_MULI16:
    case OP_MULU16:
    case OP_MULI32:
    case OP_MULU32:
    case OP_MULI64:
    case OP_MULU64:
    case OP_MULF32:
    case OP_MULF64:
    case OP_MODI8:
    case OP_MODU8:
    case OP_MODI16:
    case OP_MODU16:
    case OP_MODI32:
    case OP_MODU32:
    case OP_MODI64:
    case OP_MODU64:
    case OP_MODF32:
    case OP_MODF64:
    case OP_POWI8:
    case OP_POWU8:
    case OP_POWI16:
    case OP_POWU16:
    case OP_POWI32:
    case OP_POWU32:
    case OP_POWI64:
    case OP_POWU64:
    case OP_POWF32:
    case OP_POWF64:
    case OP_EQ8:
    case OP_EQ16:
    case OP_EQ32:
    case OP_EQ64:
    case OP_NEQ8:
    case OP_NEQ16:
    case OP_NEQ32:
    case OP_NEQ64:
    case OP_GTI8:
    case OP_GTU8:
    case OP_GTI16:
    case OP_GTU16:
    case OP_GTI32:
    case OP_GTU32:
    case OP_GTI64:
    case OP_GTU64:
    case OP_GTF32:
    case OP_GTF64:
    case OP_GTARR:
    case OP_GTEI8:
    case OP_GTEU8:
    case OP_GTEI16:
    case OP_GTEU16:
    case OP_GTEI32:
    case OP_GTEU32:
    case OP_GTEI64:
    case OP_GTEU64:
    case OP_GTEF32:
    case OP_GTEF64:
    case OP_GTEARR:
    case OP_LTI8:
    case OP_LTU8:
    case OP_LTI16:
    case OP_LTU16:
    case OP_LTI32:
    case OP_LTU32:
    case OP_LTI64:
    case OP_LTU64:
    case OP_LTF32:
    case OP_LTF64:
    case OP_LTARR:
    case OP_LTEI8:
    case OP_LTEU8:
    case OP_LTEI16:
    case OP_LTEU16:
    case OP_LTEI32:
    case OP_LTEU32:
    case OP_LTEI64:
    case OP_LTEU64:
    case OP_LTEF32:
    case OP_LTEF64:
    case OP_LTEARR:
    case OP_STRREP8:
    case OP_STRREP16:
    case OP_STRREP32:
    case OP_STRREP64:
      return 3 + LENGTH_OPCODE;
    case OP_PUSHLINE:
    case OP_JMP:
      return 4 + LENGTH_OPCODE;
    case OP_JMPI0:
    case OP_JMPN0:
    case OP_LOADCONST32:
    case OP_STORECONST8:
    case OP_GSTORECONST8:
    case OP_OBJALLOC:
    case OP_LFUNCLOOKUP:
      return 5 + LENGTH_OPCODE;
    case OP_STORECONST16:
    case OP_GSTORECONST16:
    case OP_READOBJ8:
    case OP_READOBJ16:
    case OP_READOBJ32:
    case OP_READOBJ64:
    case OP_WRITEOBJ8:
    case OP_WRITEOBJ16:
    case OP_WRITEOBJ32:
    case OP_WRITEOBJ64:
      return 6 + LENGTH_OPCODE;
    case OP_LOADCONST64:
    case OP_EQARR:
    case OP_EQSTRUCT:
    case OP_NEQARR:
    case OP_NEQSTRUCT:
    case OP_STRCONCAT:
      return 7 + LENGTH_OPCODE;
    case OP_STORECONST32:
    case OP_GSTORECONST32:
    case OP_SETARGTYPE:
      return 8 + LENGTH_OPCODE;
    case OP_LOADCONSTSTR:
    case OP_SREAD8:
    case OP_SREAD16:
    case OP_SREAD32:
    case OP_SREAD64:
    case OP_SWRITE8:
    case OP_SWRITE16:
    case OP_SWRITE32:
    case OP_SWRITE64:
    case OP_GREAD8:
    case OP_GREAD16:
    case OP_GREAD32:
    case OP_GREAD64:
    case OP_GWRITE8:
    case OP_GWRITE16:
    case OP_GWRITE32:
    case OP_GWRITE64:
    case OP_ARRAYALLOC:
      return 9 + LENGTH_OPCODE;
    case OP_STORECONST64:
    case OP_GSTORECONST64:
    case OP_CREAD8:
    case OP_CREAD16:
    case OP_CREAD32:
    case OP_CREAD64:
    case OP_CWRITE8:
    case OP_CWRITE16:
    case OP_CWRITE32:
    case OP_CWRITE64:
      return 10 + LENGTH_OPCODE;
    case OP_NFUNCLOOKUP:
      return 13 + LENGTH_OPCODE;
    default:
      return 0;
  }
}