#ifndef OPCODE_PRINTER_H
#define OPCODE_PRINTER_H

#include <cstdio>

#include "opcodes.h"

//
// This file was automatically generated by a deno script in:
// ./deno-code-gen
//

void printInstructionToString(uint8* buf, FILE* out, uint8* strPool);

#endif // OPCODE_PRINTER_H