#ifndef QUICKSCRIPT_REGISTERS_H
#define QUICKSCRIPT_REGISTERS_H

#define REGISTER_RETURN_VALUE  0
#define REGISTER_INSTR_COUNTER 1
#define FIRST_NON_RESERVED_REGISTER 2
#define REGISTER_COUNT 64
#define REGISTER_SIZE_BITS 64
#define REGISTER_SIZE_BYTES 8
#define REGISTERS_MEMSIZE (REGISTER_COUNT * REGISTER_SIZE_BYTES)

#define REGISTRY_MASK(x) (1LL << x)

typedef uint8 RegisterId;
typedef int8 RegisterIdOpt;
typedef uint64 RegisterBitSet;
typedef uint64 RegisterValue;

#endif //QUICKSCRIPT_REGISTERS_H
