#ifndef QS_TYPE_CONV_H
#define QS_TYPE_CONV_H

//
// This file was automatically generated by a deno script in:
// ./deno-code-gen
//

#include "qs/interpreter/opcodes.hpp"
#include "qs/types/types.hpp"

opcode conversionOpCode(primitivekind from, primitivekind to);

#endif //QS_TYPE_CONV_H