cmake_minimum_required(VERSION 4.2)
project(qsengine)

set(CMAKE_CXX_STANDARD 20)

add_library(qsengine STATIC
        include/qs/allocator.hpp
        include/qs/analysis/analyzer.hpp
        include/qs/analysis/SemanticContext.hpp
        include/qs/analysis/semantictree.hpp
        include/qs/analysis/transformer.hpp
        include/qs/bytecode/bytecode_file.hpp
        include/qs/bytecode/bytecode_functable.hpp
        include/qs/bytecode/bytecode_symbol.hpp
        include/qs/bytecode/bytecode_typetable.hpp
        include/qs/codegen/compiler.hpp
        include/qs/codegen/CompilerContext.hpp
        include/qs/codegen/type_conv.hpp
        include/qs/common.hpp
        include/qs/compiler_opts.hpp
        include/qs/errors.hpp
        include/qs/interpreter/heap_mem.hpp
        include/qs/interpreter/interpreter.hpp
        include/qs/interpreter/opcode_printer.hpp
        include/qs/interpreter/opcodes.hpp
        include/qs/interpreter/registers.hpp
        include/qs/interpreter/script_error.hpp
        include/qs/interpreter/StackMemory.hpp
        include/qs/interpreter/StringPool.hpp
        include/qs/nativeinterface.hpp
        include/qs/objects.hpp
        include/qs/parse/JsonPrinter.hpp
        include/qs/parse/keyw_lookup.hpp
        include/qs/parse/lexer.hpp
        include/qs/parse/parser.hpp
        include/qs/parse/print-visitor.hpp
        include/qs/parse/syntaxtree.hpp
        include/qs/parse/token.hpp
        include/qs/qs_math.hpp
        include/qs/qsenv.hpp
        include/qs/stdlib/qs_stdlib.hpp
        include/qs/strings/stringreader.hpp
        include/qs/strings/strings.hpp
        include/qs/strings/unicode_binary_props.hpp
        include/qs/strings/utf8.hpp
        include/qs/stringtable.hpp
        include/qs/types/ConstTypes.hpp
        include/qs/types/FunctionSignature.hpp
        include/qs/types/NullableType.hpp
        include/qs/types/PrimitiveScriptType.hpp
        include/qs/types/ScriptArrayType.hpp
        include/qs/types/ScriptClosureType.hpp
        include/qs/types/ScriptErroneousType.hpp
        include/qs/types/ScriptStringType.hpp
        include/qs/types/ScriptStructType.hpp
        include/qs/types/ScriptType.hpp
        include/qs/types/types.hpp
        include/qs/types/TypeTable.hpp
        include/qs/types/VoidScriptType.hpp
        src/analysis/analyzer.cpp
        src/analysis/SemanticContext.cpp
        src/analysis/semantictree.cpp
        src/analysis/transformer.cpp
        src/bytecode/bytecode_file.cpp
        src/bytecode/bytecode_typetable.cpp
        src/codegen/compiler.cpp
        src/codegen/CompilerContext.cpp
        src/codegen/type_conv.cpp
        src/errors.cpp
        src/interpreter/heap_mem.cpp
        src/interpreter/interpreter.cpp
        src/interpreter/opcode_printer.cpp
        src/interpreter/opcodes.cpp
        src/interpreter/script_error.cpp
        src/interpreter/StackMemory.cpp
        src/interpreter/StringPool.cpp
        src/nativeinterface.cpp
        src/objects.cpp
        src/parse/JsonPrinter.cpp
        src/parse/keyw_lookup.cpp
        src/parse/lexer.cpp
        src/parse/parser.cpp
        src/parse/syntaxtree.cpp
        src/parse/token.cpp
        src/qsenv.cpp
        src/stdlib/qs_stdlib.cpp
        src/strings/stringreader.cpp
        src/strings/strings.cpp
        src/strings/unicode_binary_props.cpp
        src/strings/utf8.cpp
        src/stringtable.cpp
        src/types/ConstTypes.cpp
        src/types/FunctionSignature.cpp
        src/types/PrimitiveScriptType.cpp
        src/types/ScriptArrayType.cpp
        src/types/ScriptClosureType.cpp
        src/types/ScriptErroneousType.cpp
        src/types/ScriptStringType.cpp
        src/types/ScriptStructType.cpp
        src/types/ScriptType.cpp
        src/types/types.cpp
        src/types/TypeTable.cpp
        src/types/VoidScriptType.cpp
)

target_include_directories(qsengine PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)