#ifndef UNICODE_BINARY_PROPS_H
#define UNICODE_BINARY_PROPS_H

#include "../common.h"
#include "utf8.h"

//
// This file was automatically generated by a deno script in:
// ./deno-code-gen
//

typedef const uint8* UnicodeBitSet;

#define BPROP_Alphabetic 0
#define BPROP_Cased 1
#define BPROP_Case_Ignorable 2
#define BPROP_Changes_When_Casefolded 3
#define BPROP_Changes_When_Casemapped 4
#define BPROP_Changes_When_Lowercased 5
#define BPROP_Changes_When_Titlecased 6
#define BPROP_Changes_When_Uppercased 7
#define BPROP_Default_Ignorable_Code_Point 8
#define BPROP_Diacritic 9
#define BPROP_Emoji_Modifier_Base 10
#define BPROP_Emoji_Component 11
#define BPROP_Emoji 12
#define BPROP_Emoji_Presentation 13
#define BPROP_Extender 14
#define BPROP_Extended_Pictographic 15
#define BPROP_Grapheme_Base 16
#define BPROP_Grapheme_Extend 17
#define BPROP_Grapheme_Link 18
#define BPROP_ID_Continue 19
#define BPROP_Ideographic 20
#define BPROP_ID_Start 21
#define BPROP_Lowercase 22
#define BPROP_Math 23
#define BPROP_Noncharacter_Code_Point 24
#define BPROP_Other_Alphabetic 25
#define BPROP_Other_Default_Ignorable_Code_Point 26
#define BPROP_Other_Grapheme_Extend 27
#define BPROP_Other_Lowercase 28
#define BPROP_Other_Math 29
#define BPROP_Other_Uppercase 30
#define BPROP_Pattern_Syntax 31
#define BPROP_Radical 32
#define BPROP_Soft_Dotted 33
#define BPROP_Sentence_Terminal 34
#define BPROP_Terminal_Punctuation 35
#define BPROP_Unified_Ideograph 36
#define BPROP_Uppercase 37
#define BPROP_Variation_Selector 38
#define BPROP_XID_Continue 39
#define BPROP_XID_Start 40
#define BPROP_ASCII_Hex_Digit 0
#define BPROP_Bidi_Control 2
#define BPROP_Dash 14
#define BPROP_Deprecated 15
#define BPROP_Emoji_Modifier 20
#define BPROP_Hex_Digit 28
#define BPROP_Hyphen 29
#define BPROP_ID_Compat_Math_Continue 30
#define BPROP_ID_Compat_Math_Start 31
#define BPROP_IDS_Binary_Operator 35
#define BPROP_IDS_Trinary_Operator 36
#define BPROP_IDS_Unary_Operator 37
#define BPROP_Join_Control 38
#define BPROP_Logical_Order_Exception 41
#define BPROP_Modifier_Combining_Mark 44
#define BPROP_Other_ID_Continue 49
#define BPROP_Other_ID_Start 50
#define BPROP_Pattern_White_Space 55
#define BPROP_Prepended_Concatenation_Mark 56
#define BPROP_Quotation_Mark 57
#define BPROP_Regional_Indicator 59
#define BPROP_White_Space 66
typedef uint8 binaryprop;

bool ucIsAlphabetic(utf32char ch);

bool ucIsCased(utf32char ch);

bool ucIsCaseIgnorable(utf32char ch);

bool ucChangesWhenCasefolded(utf32char ch);

bool ucChangesWhenCasemapped(utf32char ch);

bool ucChangesWhenLowercased(utf32char ch);

bool ucChangesWhenTitlecased(utf32char ch);

bool ucChangesWhenUppercased(utf32char ch);

bool ucIsDefaultIgnorableCodePoint(utf32char ch);

bool ucIsDiacritic(utf32char ch);

bool ucIsEmojiModifierBase(utf32char ch);

bool ucIsEmojiComponent(utf32char ch);

bool ucIsEmoji(utf32char ch);

bool ucIsEmojiPresentation(utf32char ch);

bool ucIsExtender(utf32char ch);

bool ucIsExtendedPictographic(utf32char ch);

bool ucIsGraphemeBase(utf32char ch);

bool ucIsGraphemeExtend(utf32char ch);

bool ucIsGraphemeLink(utf32char ch);

bool ucIsIdContinue(utf32char ch);

bool ucIsIdeographic(utf32char ch);

bool ucIsIdStart(utf32char ch);

bool ucIsLowercase(utf32char ch);

bool ucIsMath(utf32char ch);

bool ucIsNoncharacterCodePoint(utf32char ch);

bool ucIsOtherAlphabetic(utf32char ch);

bool ucIsOtherDefaultIgnorableCodePoint(utf32char ch);

bool ucIsOtherGraphemeExtend(utf32char ch);

bool ucIsOtherLowercase(utf32char ch);

bool ucIsOtherMath(utf32char ch);

bool ucIsOtherUppercase(utf32char ch);

bool ucIsPatternSyntax(utf32char ch);

bool ucIsRadical(utf32char ch);

bool ucIsSoftDotted(utf32char ch);

bool ucIsSentenceTerminal(utf32char ch);

bool ucIsTerminalPunctuation(utf32char ch);

bool ucIsUnifiedIdeograph(utf32char ch);

bool ucIsUppercase(utf32char ch);

bool ucIsVariationSelector(utf32char ch);

bool ucIsXidContinue(utf32char ch);

bool ucIsXidStart(utf32char ch);

bool ucIsAsciiHexDigit(utf32char ch);

bool ucIsBidiControl(utf32char ch);

bool ucIsDash(utf32char ch);

bool ucIsDeprecated(utf32char ch);

bool ucIsEmojiModifier(utf32char ch);

bool ucIsHexDigit(utf32char ch);

bool ucIsHyphen(utf32char ch);

bool ucIsIdCompatMathContinue(utf32char ch);

bool ucIsIdCompatMathStart(utf32char ch);

bool ucIsIdsBinaryOperator(utf32char ch);

bool ucIsIdsTrinaryOperator(utf32char ch);

bool ucIsIdsUnaryOperator(utf32char ch);

bool ucIsJoinControl(utf32char ch);

bool ucIsLogicalOrderException(utf32char ch);

bool ucIsModifierCombiningMark(utf32char ch);

bool ucIsOtherIdContinue(utf32char ch);

bool ucIsOtherIdStart(utf32char ch);

bool ucIsPatternWhiteSpace(utf32char ch);

bool ucIsPrependedConcatenationMark(utf32char ch);

bool ucIsQuotationMark(utf32char ch);

bool ucIsRegionalIndicator(utf32char ch);

bool ucIsWhiteSpace(utf32char ch);

#endif // UNICODE_BINARY_PROPS_H