export interface InstructionParam {
  typename: string
  size: number
  name: string
}

export interface Instruction {
  opcode: string
  value: string
  params: InstructionParam[]
  category: string
  padding: number
  cSourceCode?: string[]
}

export interface NumericType {
  bitSize: number
  byteSize: number
  signed: boolean
  integral: boolean
  shorthand: string
  fullname: string
}

export interface OpCodeGenResult {
  codes: Instruction[]
  baseType: string
  opcodeSize: number
}

export const NO_ARGS: InstructionParam[] = []
export const UNARY_ARGS: InstructionParam[] = [
  {size: 1, name: "in", typename: "register"},
  {size: 1, name: "out", typename: "register"}
]
export const BINARY_ARGS: InstructionParam[] = [
  {size: 1, name: "lhs", typename: "register"},
  {size: 1, name: "rhs", typename: "register"},
  {size: 1, name: "out", typename: "register"},
]

export const NUMBER_TYPES: NumericType[] = generateNumberTypes()

export const INSTRUCTION_LENGTH: number = 16

export const FILE_HEADER = `//\n// This file was automatically generated by a deno script in:\n// ./deno-code-gen\n//`

function generateNumberTypes(): NumericType[] {
  let arr: NumericType[] = []

  const integralSizes = [1, 2, 4, 8]
  const floatSizes = [4, 8]

  for (const size of integralSizes) {
    const bitSize = size * 8

    for (const s of [true, false]) {
      let name = `${s ? '' : 'u'}int${bitSize}`
      arr.push({
        bitSize,
        byteSize: size,
        fullname: name,
        shorthand: `${name[0].toUpperCase()}${bitSize}`,
        integral: true,
        signed: s
      })
    }
  }
  for (const fs of floatSizes) {
    const bitSize = fs * 8
    arr.push({
      bitSize,
      byteSize: fs,
      fullname: `float${bitSize}`,
      shorthand: `F${bitSize}`,
      integral: false,
      signed: true
    })
  }

  return arr
}

export async function writeToFile(out: string, fname: string): Promise<void> {
  // @ts-ignore
  await Deno.writeTextFile(fname, out)
  console.log(`Wrote to file ${fname}`)
}

export function getFittingType(n: number): {bytes: number, type: string} | null {
  const potentialSizes = [1, 2, 4, 8]

  for (const sz of potentialSizes) {
    let max = parseInt("FF".repeat(sz), 16)

    if (n > max) {
      continue
    }

    const memSize = sz
    const baseType = `uint${sz * 8}`

    return {bytes: memSize, type: baseType}
  }

  return null
}