interface InstructionParam {
  typename: string
  size: number
  name: string
}

interface OpCodePadding {
  opcode: string
  padding: number
}

interface Instruction extends OpCodePadding{
  value: string
  params: InstructionParam[]
  category: string
}

interface OpCodeGenResult {
  opcodes: Instruction[]
  paddings: OpCodePadding[]
}

interface NumericType {
  shorthand: string
  fullname: string
  size: number
}

const NUMBER_TYPES: NumericType[] = [
  {shorthand: "I8", fullname: "int8", size: 8},
  {shorthand: "U8", fullname: "uint8", size: 8},
  {shorthand: "I16", fullname: "int16", size: 16},
  {shorthand: "U16", fullname: "uint16", size: 16},
  {shorthand: "I32", fullname: "int32", size: 32},
  {shorthand: "U32", fullname: "uint32", size: 32},
  {shorthand: "I64", fullname: "int64", size: 64},
  {shorthand: "U64", fullname: "uint64", size: 64},
  {shorthand: "F32", fullname: "float32", size: 32},
  {shorthand: "F64", fullname: "float64", size: 64}
]

const ARGUMENTS_LENGTH = 9

const FILE_HEADER = `//\n// This file was automatically generated by a deno script in:\n// deno-scripts/opcode-gen.ts\n//`

function generateOpCodes(): OpCodeGenResult {
  let currentCategory: string = ""
  let addToPadding = true

  const opcodes: Instruction[] = []
  const paddings: OpCodePadding[] = []

  function getPadding(params: InstructionParam[]): number {
    let pad = ARGUMENTS_LENGTH
    for (const p of params) {
      pad -= p.size
    }
    return pad
  }

  function opCode(name: string, ...params: InstructionParam[]) {
    const numval = `0x${(opcodes.length).toString(16).toUpperCase().padStart(4, "0")}`
    const pad = getPadding(params)

    let instr: Instruction = {
      opcode: name,
      padding: pad,
      params,
      value: numval,
      category: currentCategory
    }

    opcodes.push(instr)

    if (addToPadding) {
      paddings.push(instr)
    }
  }

  function byteSizedOpCode(name: string, ...params: InstructionParam[]): void {
    const sizes = [8, 16, 32, 64]
    const bytesizes = [1, 2, 4, 6]

    let hasTypeVariance = false
    for (const p of params) {
      if (p.size == -1) {
        hasTypeVariance = true
        break
      }
    }

    if (!hasTypeVariance && addToPadding) {
      paddings.push({
        opcode: name,
        padding: getPadding(params)
      })
    }

    for (let i = 0; i < sizes.length; i++) {
      const p: InstructionParam[] = []

      const size: number = sizes[i]
      const bsize: number = bytesizes[i]

      for (const param of params) {
        if (param.size == -1) {
          p.push({
            name: param.name,
            size: bsize,
            typename: `uint${size}`
          })
          continue
        }
        p.push({...param})
      }

      opCode(`${name}${size}`, ...p)
    }
  }

  function reg(name: string): InstructionParam {
    return {size: 1, typename: "register", name}
  }
  function uint32(name: string): InstructionParam {
    return {size: 4, typename: "uint32", name}
  }
  function uint64(name: string): InstructionParam {
    return {size: 8, typename: "uint64", name}
  }
  function sd(name: string): InstructionParam {
    return {name, size: -1, typename: ""}
  }
  function binParams(): InstructionParam[] {
    return [reg("lhs"), reg("rhs"), reg("out")]
  }
  function unaryParams(): InstructionParam[] {
    return [reg("in"), reg("out")]
  }

  currentCategory = "4.3.1 General Purpose OP Codes"
  opCode("NOP")

  opCode("PUSHLINE", uint32("lineno"))
  opCode("RET")
  opCode("JMP", uint32("to"))
  opCode("JMPI0", uint32("to"), reg("condition"))
  opCode("JMPN0", uint32("to"), reg("condition"))
  opCode("MOV", reg("from"), reg("to"))

  byteSizedOpCode("LOADCONST", reg("out"), sd("val"))
  opCode("LOADCONSTSTR", reg("out"), uint64("straddr"))

  currentCategory = "4.3.2 Stack Memory OP Codes"
  opCode("STACKALLOC", uint64("bytes"))
  opCode("STACKFREE", uint64("bytes"))
  byteSizedOpCode("RSREAD", reg("out"), uint64("offset"))
  byteSizedOpCode("RSWRITE", reg("val"), uint64("offset"))
  byteSizedOpCode("ASREAD", reg("out"), uint64("offset"))
  byteSizedOpCode("ASWRITE", reg("val"), uint64("offset"))

  currentCategory = "4.3.3 Heap Memory OP Codes"
  opCode("HEAPALLOC", reg("out"), uint64("bytes"))
  opCode("HEAPFREE", reg("addr"), uint64("bytes"))
  byteSizedOpCode("READOBJ", reg("obj"), reg("out"), uint32("off"))
  byteSizedOpCode("WRITEOBJ", reg("obj"), reg("val"), uint32("off"))
  byteSizedOpCode("READIDX", reg("obj"), reg("out"), reg("idx"))
  byteSizedOpCode("WRITEIDX", reg("obj"), reg("val"), reg("idx"))

  currentCategory = "4.3.4 Function Call Instructions"
  opCode("PUSHARG", reg("val"))
  opCode("SETRV", reg("val"))
  opCode("INVOKE", reg("func"), reg("out"))

  const mathOperations = [
    "add",
    "sub",
    "div",
    "mul",
    "mod",
    "pow",
  ]

  currentCategory = "4.3.5 Conversion Instructions"
  const unaryPad = getPadding(unaryParams())

  addToPadding = false
  paddings.push({padding: unaryPad, opcode: "CAST"})

  for (const f of NUMBER_TYPES) {
    for (const t of NUMBER_TYPES) {
      if (f == t) {
        continue
      }

      if (f.shorthand.startsWith("U") && t.shorthand.startsWith("U")) {
        // No converting between unsigned types, just
        // truncate bits or add extra leading bits
        continue
      }

      opCode(`${f.shorthand}T${t.shorthand}`, ...unaryParams())
    }
  }
  addToPadding = true

  currentCategory = "4.3.6 Unary Operations"

  opCode("BNEGATE", ...unaryParams())
  opCode("LNEGATE", ...unaryParams())

  const numberUnaryOperations = ["NEG", "INC", "DEC"]

  addToPadding = false;
  for (const op of numberUnaryOperations) {
    paddings.push({opcode: op, padding: unaryPad})
    for (const ts of NUMBER_TYPES) {
      opCode(`${op}${ts.shorthand}`, ...unaryParams())
    }
  }
  addToPadding = true

  currentCategory = "4.3.7.1 Integer-only Binary Operations"
  byteSizedOpCode("LSHIFT", ...binParams())
  byteSizedOpCode("RSHIFT", ...binParams())
  byteSizedOpCode("URSHIFT", ...binParams())

  currentCategory = "4.3.7.2 Boolean-only Binary Operations"
  opCode("BAND", ...binParams())
  opCode("BOR", ...binParams())
  opCode("BXOR", ...binParams())
  opCode("LAND", ...binParams())
  opCode("LOR", ...binParams())
  opCode("LXOR", ...binParams())

  currentCategory = "4.3.7.3 General Number Binary Operations"
  addToPadding = false

  const binPadding = getPadding(binParams())

  for (const mathOp of mathOperations) {
    paddings.push({opcode: mathOp.toUpperCase(), padding: binPadding})
    for (const type of NUMBER_TYPES) {
      opCode(`${mathOp.toUpperCase()}${type.shorthand}`, ...binParams())
    }
  }

  currentCategory = "4.3.7.4 Comparison Operations"
  const equalityOperators = ["EQ", "NEQ"]
  for (const eqOp of equalityOperators) {
    paddings.push({opcode: eqOp, padding: binPadding})
    byteSizedOpCode(eqOp, ...binParams())
    opCode(`${eqOp}ARR`, ...binParams())
    opCode(`${eqOp}STRUCT`, ...binParams())
  }

  const comparisonOperators = ["GT", "GTE", "LT", "LTE"]

  for (const cmpOp of comparisonOperators) {
    for (const ts of NUMBER_TYPES) {
      opCode(`${cmpOp}${ts.shorthand}`, ...binParams())
    }
    opCode(`${cmpOp}ARR`, ...binParams())
    paddings.push({opcode: cmpOp, padding: binPadding})
  }

  currentCategory = "4.3.7.5 String/Array Operations"
  addToPadding = true

  opCode("STRCONCAT", ...binParams())
  byteSizedOpCode("STRREP", ...binParams())

  return {opcodes, paddings}
}

async function createOpCodesHeader(res: OpCodeGenResult): Promise<void> {
  const opcodes = res.opcodes
  const paddings = res.paddings

  let out = ``

  out += "\n\n"
  out += FILE_HEADER
  out += `\n// Section numbers that you see here are references to this:`
  out += `\n// https://juliewoolie.com/blog/quickscript`
  out += `\n// I wrote a bunch of the specification and planning there`
  out += `\n//`

  const groupedCodes: {[cat: string]: Instruction[]} = {}

  opcodes.forEach(v => {
    let arr = groupedCodes[v.category]
    if (!arr) {
      arr = []
      groupedCodes[v.category] = arr
    }
    arr.push(v)
  })

  for (const group in groupedCodes) {
    out += `\n\n// ${group}`
    for (const code of groupedCodes[group]) {
      out += `\n#define OP_${code.opcode.padEnd(15, ' ')} ${code.value}`
    }
  }

  out += `\n`
  const paddingDejavu: {[key: string]: number} = {}
  for (const code of paddings) {
    let opcode = code.opcode;

    if (endsWith(opcode, "16", "32", "64")) {
      opcode = opcode.substring(0, opcode.length - 2)
    } else if (endsWith(opcode, "8")) {
      opcode = opcode.substring(0, opcode.length - 1)
    }

    let printedPad = paddingDejavu[opcode]
    if (printedPad != undefined && printedPad == code.padding) {
      continue
    }

    out += `\n#define PAD_${code.opcode.padEnd(14, ' ')} ${code.padding}`
    paddingDejavu[code.opcode] = code.padding
  }

  let opcodeLen: number
  let basetype: string

  if (opcodes.length < 256) {
    opcodeLen = 1
    basetype = "uint8"
  } else {
    opcodeLen = 2
    basetype = "uint16"
  }

  const instructionLen = opcodeLen + ARGUMENTS_LENGTH

  out = `#ifndef QUICKSCRIPT_OPCODES_H
#define QUICKSCRIPT_OPCODES_H

#include "../common.h"

#define LENGTH_OPCODE ${opcodeLen}
#define LENGTH_ARGS ${ARGUMENTS_LENGTH}
#define LENGTH_INSTRUCTION ${instructionLen}` + out

  out += `\n\ntypedef ${basetype} opcode;\n\nconststring opcode_name(opcode code);`
  out += `\n\n#endif //QUICKSCRIPT_OPCODES_H`

  await writeToFile(out, "../src/interpreter/opcodes.h")
}

async function createOpCodesSourceFile(opcodes: Instruction[]): Promise<void> {
  let out = `#include "opcodes.h"

${FILE_HEADER}

conststring opcode_name(opcode code) {
  switch (code) {`

  for (const code of opcodes) {
    if (code.opcode == "NOP") {
      continue
    }
    out += `\n    case OP_${code.opcode}: return "${code.opcode}";`
  }
  out += `
    default: return "NOP";
  }
}
`
  await writeToFile(out, "../src/interpreter/opcodes.cc")
}

async function createSpecHeader(): Promise<void> {
  let out = `#ifndef QUICKSCRIPT_OPCODESPEC_H
#define QUICKSCRIPT_OPCODESPEC_H

${FILE_HEADER}

#include <cstdarg>
#include "../interpreter/opcodes.h"

void appendOpCodeData(uint8* buf, opcode code, va_list list);

#endif //QUICKSCRIPT_OPCODESPEC_H`

  await writeToFile(out, "../src/codegen/opcodespec.h")
}

async function createSpecSourceFile(opcodes: Instruction[]): Promise<void> {
  let out = `#include "opcodespec.h"
#include <cstring>

${FILE_HEADER}

void appendOpCodeData(uint8* buf, opcode code, va_list list) {
  switch (code) {`

  const opcodeGroups: {[sig: string]: Instruction[]} = {}

  for (const code of opcodes) {
    const params = code.params;
    let sig = ""
    params.forEach((v, i) => {
      if (i != 0) {
        sig += ","
      }
      sig += `${v.typename}`
    })

    let arr: Instruction[] | undefined = opcodeGroups[sig]
    if (!arr) {
      arr = []
      opcodeGroups[sig] = arr
    }

    arr.push(code)
  }

  const castingRequiredTypes = ["uint8", "uint16"]

  for (const sig in opcodeGroups) {
    let arr = opcodeGroups[sig]
    const c = arr[0]

    out += `\n\n    //`
    out += `\n    // Padding: ${c.padding}`
    out += `\n    // Arguments:`

    c.params.forEach((v, i) => {
      out += `\n    //   [${i}] ${v.typename}`
    })
    out += `\n    //`

    for (const code of arr) {
      out += `\n    case OP_${code.opcode}:`
    }

    let off = 0
    for (const p of c.params) {
      let typename = p.typename
      let mustCast = true
      let mustCastArg = false
      let varname: string = "buf"

      if (off != 0) {
        varname += ` + ${off}`
      }

      if (typename == "register") {
        typename = "uint8"
        mustCast = false
        mustCastArg = true
      } else if (typename == "uint8") {
        mustCast = false
        mustCastArg = true
      }

      out += `\n      *`
      if (mustCast) {
        out += `reinterpret_cast<${typename}*>`
      }
      if (mustCast || off > 0) {
        out += "("
      }
      out += `${varname}`
      if (mustCast || off > 0) {
        out += `)`
      }

      let vaArgCallType: string = typename
      if (castingRequiredTypes.includes(typename)) {
        vaArgCallType = "int32"
      }

      out += ` = `
      if (mustCastArg) {
        out += `static_cast<${typename}>(`
      }
      out += `va_arg(list, ${vaArgCallType})`
      if (mustCastArg) {
        out += `)`
      }
      out += `;`

      off += p.size
    }

    if (c.padding > 0) {
      let varname: string = "buf"
      if (off != 0) {
        varname += ` + ${off}`
      }

      out += `\n      memset(${varname}, 0, ${c.padding});`
    }

    out += `\n      break;`
  }


  out += `\n\n    default:\n      break;\n  }\n}`

  await writeToFile(out, "../src/codegen/opcodespec.cc")
}

async function generateMarkdownSpec(opcodes: Instruction[]): Promise<void> {
  let out = `# OP Code specification Table
| OP Code | Value | Padding | Arguments |
|--|--|--|--|`
  for (const code of opcodes) {
    out += `\n|\`${code.opcode}\`|\`${code.value}\`|${code.padding}|`
    code.params.forEach((v, i) => {
      if (i != 0) {
        out += `, `
      }
      out += `\`${v.name}: ${v.typename}\``
    })
    out += "|"
  }

  await writeToFile(out, "../opcode-spec.md")
}

function printHtmlSpec(opcodes: Instruction[]): void {
  let out = `<table>
  <caption>OP Codes</caption>
  <thead><tr>
    <th>OP Code</th>
    <th>Value</th>
    <th>Padding</th>
    <th>Arguments</th>
  </tr></thead>
  <tbody>`

  for (const code of opcodes) {
    let paramStr = ""
    code.params.forEach((v, i) => {
      if (i != 0) {
        paramStr += ", "
      }
      paramStr += `${v.name}: ${v.typename}`
    })

    out += `
    <tr><td><code>${code.opcode}</code></td><td><code>${code.value}</code></td><td>${code.padding}</td><td><code>${paramStr}</code></td></tr>`
  }

  out += `\n  </tbody>\n</table>`
  console.log(out)
}

async function generateConversionCompileMethod(): Promise<void> {
  let out = `#ifndef QUICKSCRIPT_TYPE_CONV_H
#define QUICKSCRIPT_TYPE_CONV_H

${FILE_HEADER}

#include "../interpreter/opcodes.h"
#include "../types.h"

opcode conversionOpCode(primitivekind from, primitivekind to);

#endif // QUICKSCRIPT_TYPE_CONV_H`

  await writeToFile(out, "../src/codegen/type_conv.h")

  out = `
#include "type_conv.h"
  
${FILE_HEADER}

opcode conversionOpCode(primitivekind from, primitivekind to) {
  switch (from) {`

  for (const fromtype of NUMBER_TYPES) {
    if (fromtype.shorthand == "U8") {
      out += `\n    case PK_BOOL:`
    }
    out += `\n    case PK_${fromtype.fullname.toUpperCase()}:\n      switch(to) {`
    for (const totype of NUMBER_TYPES) {
      if (fromtype == totype) {
        continue
      }
      if (fromtype.shorthand.startsWith("U")
          && totype.shorthand.startsWith("U")
      ) {
        continue
      }

      const opcode = `${fromtype.shorthand}T${totype.shorthand}`

      out += `\n        case PK_${totype.fullname.toUpperCase()}: return OP_${opcode};`
    }
    out += `\n        default: return OP_NOP;`
    out += `\n      }`
    out += `\n      return OP_NOP;`
  }

  out += `
    default: return OP_NOP;
  }
}`

  await writeToFile(out, "../src/codegen/type_conv.cc")
}

async function main(): Promise<void> {
  const res = generateOpCodes()
  const codes = res.opcodes

  await createOpCodesHeader(res)
  await createOpCodesSourceFile(codes)

  await createSpecHeader()
  await createSpecSourceFile(codes)

  await generateMarkdownSpec(codes)

  printHtmlSpec(codes)

  generateConversionCompileMethod()
}

function endsWith(str: string, ...suffixes: string[]): boolean {
  for (const suffix of suffixes) {
    if (str.endsWith(suffix)) {
      return true
    }
  }
  return false
}

async function writeToFile(out: string, fname: string): Promise<void> {
  // @ts-ignore
  await Deno.writeTextFile(fname, out)
}

// @ts-ignore
await main()