#ifndef QUICKSCRIPT_OPCODESPEC_H
#define QUICKSCRIPT_OPCODESPEC_H

//
// This file was automatically generated by a deno script in:
// deno-scripts/opcode-gen.ts
//

#include <cstdarg>
#include "../interpreter/opcodes.h"

void appendOpCodeData(uint8* buf, opcode code, va_list list);

#endif //QUICKSCRIPT_OPCODESPEC_H