#include "opcodespec.h"
#include <cstring>

//
// This file was automatically generated by a deno script in:
// deno-scripts/opcode-gen.ts
// 

void appendOpCodeData(uint8* buf, opcode code, va_list list) {
  switch (code) {

    //
    // Padding: 9
    // Arguments:
    //
    case OP_NOP:
    case OP_RET:
      memset(buf, 0, 9);
      break;

    //
    // Padding: 5
    // Arguments:
    //   [0] lineno: uint32
    //
    case OP_PUSHLINE:
      *reinterpret_cast<uint32*>(buf) = va_arg(list, uint32);
      memset(buf + 4, 0, 5);
      break;

    //
    // Padding: 5
    // Arguments:
    //   [0] to: uint32
    //
    case OP_JMP:
      *reinterpret_cast<uint32*>(buf) = va_arg(list, uint32);
      memset(buf + 4, 0, 5);
      break;

    //
    // Padding: 4
    // Arguments:
    //   [0] to: uint32
    //   [1] condition: register
    //
    case OP_JMPI0:
    case OP_JMPN0:
      *reinterpret_cast<uint32*>(buf) = va_arg(list, uint32);
      *(buf + 4) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 5, 0, 4);
      break;

    //
    // Padding: 7
    // Arguments:
    //   [0] from: register
    //   [1] to: register
    //
    case OP_MOV:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 2, 0, 7);
      break;

    //
    // Padding: 7
    // Arguments:
    //   [0] out: register
    //   [1] val: uint8
    //
    case OP_LOADCONST8:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 2, 0, 7);
      break;

    //
    // Padding: 6
    // Arguments:
    //   [0] out: register
    //   [1] val: uint16
    //
    case OP_LOADCONST16:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint16*>(buf + 1) = va_arg(list, int32);
      memset(buf + 3, 0, 6);
      break;

    //
    // Padding: 4
    // Arguments:
    //   [0] out: register
    //   [1] val: uint32
    //
    case OP_LOADCONST32:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint32*>(buf + 1) = va_arg(list, uint32);
      memset(buf + 5, 0, 4);
      break;

    //
    // Padding: 2
    // Arguments:
    //   [0] out: register
    //   [1] val: uint64
    //
    case OP_LOADCONST64:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint64*>(buf + 1) = va_arg(list, uint64);
      memset(buf + 7, 0, 2);
      break;

    //
    // Padding: 0
    // Arguments:
    //   [0] out: register
    //   [1] straddr: uint64
    //
    case OP_LOADCONSTSTR:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint64*>(buf + 1) = va_arg(list, uint64);
      break;

    //
    // Padding: 1
    // Arguments:
    //   [0] bytes: uint64
    //
    case OP_STACKALLOC:
    case OP_STACKFREE:
      *reinterpret_cast<uint64*>(buf) = va_arg(list, uint64);
      memset(buf + 8, 0, 1);
      break;

    //
    // Padding: 0
    // Arguments:
    //   [0] out: register
    //   [1] offset: uint64
    //
    case OP_RSREAD8:
    case OP_RSREAD16:
    case OP_RSREAD32:
    case OP_RSREAD64:
    case OP_ASREAD8:
    case OP_ASREAD16:
    case OP_ASREAD32:
    case OP_ASREAD64:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint64*>(buf + 1) = va_arg(list, uint64);
      break;

    //
    // Padding: 0
    // Arguments:
    //   [0] val: register
    //   [1] offset: uint64
    //
    case OP_RSWRITE8:
    case OP_RSWRITE16:
    case OP_RSWRITE32:
    case OP_RSWRITE64:
    case OP_ASWRITE8:
    case OP_ASWRITE16:
    case OP_ASWRITE32:
    case OP_ASWRITE64:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint64*>(buf + 1) = va_arg(list, uint64);
      break;

    //
    // Padding: 0
    // Arguments:
    //   [0] out: register
    //   [1] bytes: uint64
    //
    case OP_HEAPALLOC:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint64*>(buf + 1) = va_arg(list, uint64);
      break;

    //
    // Padding: 0
    // Arguments:
    //   [0] addr: register
    //   [1] bytes: uint64
    //
    case OP_HEAPFREE:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint64*>(buf + 1) = va_arg(list, uint64);
      break;

    //
    // Padding: 3
    // Arguments:
    //   [0] obj: register
    //   [1] out: register
    //   [2] off: uint32
    //
    case OP_READOBJ8:
    case OP_READOBJ16:
    case OP_READOBJ32:
    case OP_READOBJ64:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint32*>(buf + 2) = va_arg(list, uint32);
      memset(buf + 6, 0, 3);
      break;

    //
    // Padding: 3
    // Arguments:
    //   [0] obj: register
    //   [1] val: register
    //   [2] off: uint32
    //
    case OP_WRITEOBJ8:
    case OP_WRITEOBJ16:
    case OP_WRITEOBJ32:
    case OP_WRITEOBJ64:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      *reinterpret_cast<uint32*>(buf + 2) = va_arg(list, uint32);
      memset(buf + 6, 0, 3);
      break;

    //
    // Padding: 6
    // Arguments:
    //   [0] obj: register
    //   [1] out: register
    //   [2] idx: register
    //
    case OP_READIDX8:
    case OP_READIDX16:
    case OP_READIDX32:
    case OP_READIDX64:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      *(buf + 2) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 3, 0, 6);
      break;

    //
    // Padding: 6
    // Arguments:
    //   [0] obj: register
    //   [1] val: register
    //   [2] idx: register
    //
    case OP_WRITEIDX8:
    case OP_WRITEIDX16:
    case OP_WRITEIDX32:
    case OP_WRITEIDX64:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      *(buf + 2) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 3, 0, 6);
      break;

    //
    // Padding: 8
    // Arguments:
    //   [0] val: register
    //
    case OP_PUSHARG:
    case OP_SETRV:
    case OP_VINVOKE:
      *buf = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 1, 0, 8);
      break;

    //
    // Padding: 7
    // Arguments:
    //   [0] val: register
    //   [1] out: register
    //
    case OP_INVOKE:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 2, 0, 7);
      break;

    //
    // Padding: 7
    // Arguments:
    //   [0] from: register
    //   [1] out: register
    //
    case OP_I8TU8:
    case OP_I8TI16:
    case OP_I8TU16:
    case OP_I8TI32:
    case OP_I8TU32:
    case OP_I8TI64:
    case OP_I8TU64:
    case OP_I8TF32:
    case OP_I8TF64:
    case OP_U8TI8:
    case OP_U8TI16:
    case OP_U8TU16:
    case OP_U8TI32:
    case OP_U8TU32:
    case OP_U8TI64:
    case OP_U8TU64:
    case OP_U8TF32:
    case OP_U8TF64:
    case OP_I16TI8:
    case OP_I16TU8:
    case OP_I16TU16:
    case OP_I16TI32:
    case OP_I16TU32:
    case OP_I16TI64:
    case OP_I16TU64:
    case OP_I16TF32:
    case OP_I16TF64:
    case OP_U16TI8:
    case OP_U16TU8:
    case OP_U16TI16:
    case OP_U16TI32:
    case OP_U16TU32:
    case OP_U16TI64:
    case OP_U16TU64:
    case OP_U16TF32:
    case OP_U16TF64:
    case OP_I32TI8:
    case OP_I32TU8:
    case OP_I32TI16:
    case OP_I32TU16:
    case OP_I32TU32:
    case OP_I32TI64:
    case OP_I32TU64:
    case OP_I32TF32:
    case OP_I32TF64:
    case OP_U32TI8:
    case OP_U32TU8:
    case OP_U32TI16:
    case OP_U32TU16:
    case OP_U32TI32:
    case OP_U32TI64:
    case OP_U32TU64:
    case OP_U32TF32:
    case OP_U32TF64:
    case OP_I64TI8:
    case OP_I64TU8:
    case OP_I64TI16:
    case OP_I64TU16:
    case OP_I64TI32:
    case OP_I64TU32:
    case OP_I64TU64:
    case OP_I64TF32:
    case OP_I64TF64:
    case OP_U64TI8:
    case OP_U64TU8:
    case OP_U64TI16:
    case OP_U64TU16:
    case OP_U64TI32:
    case OP_U64TU32:
    case OP_U64TI64:
    case OP_U64TF32:
    case OP_U64TF64:
    case OP_F32TI8:
    case OP_F32TU8:
    case OP_F32TI16:
    case OP_F32TU16:
    case OP_F32TI32:
    case OP_F32TU32:
    case OP_F32TI64:
    case OP_F32TU64:
    case OP_F32TF64:
    case OP_F64TI8:
    case OP_F64TU8:
    case OP_F64TI16:
    case OP_F64TU16:
    case OP_F64TI32:
    case OP_F64TU32:
    case OP_F64TI64:
    case OP_F64TU64:
    case OP_F64TF32:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 2, 0, 7);
      break;

    //
    // Padding: 7
    // Arguments:
    //   [0] in: register
    //   [1] out: register
    //
    case OP_BNEGATE:
    case OP_LNEGATE:
    case OP_NEGI8:
    case OP_NEGU8:
    case OP_NEGI16:
    case OP_NEGU16:
    case OP_NEGI32:
    case OP_NEGU32:
    case OP_NEGI64:
    case OP_NEGU64:
    case OP_NEGF32:
    case OP_NEGF64:
    case OP_INCI8:
    case OP_INCU8:
    case OP_INCI16:
    case OP_INCU16:
    case OP_INCI32:
    case OP_INCU32:
    case OP_INCI64:
    case OP_INCU64:
    case OP_INCF32:
    case OP_INCF64:
    case OP_DECI8:
    case OP_DECU8:
    case OP_DECI16:
    case OP_DECU16:
    case OP_DECI32:
    case OP_DECU32:
    case OP_DECI64:
    case OP_DECU64:
    case OP_DECF32:
    case OP_DECF64:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 2, 0, 7);
      break;

    //
    // Padding: 6
    // Arguments:
    //   [0] lhs: register
    //   [1] rhs: register
    //   [2] out: register
    //
    case OP_LSHIFT8:
    case OP_LSHIFT16:
    case OP_LSHIFT32:
    case OP_LSHIFT64:
    case OP_URSHIFT8:
    case OP_URSHIFT16:
    case OP_URSHIFT32:
    case OP_URSHIFT64:
    case OP_BAND:
    case OP_BOR:
    case OP_BXOR:
    case OP_LAND:
    case OP_LOR:
    case OP_LXOR:
    case OP_ADDI8:
    case OP_ADDU8:
    case OP_ADDI16:
    case OP_ADDU16:
    case OP_ADDI32:
    case OP_ADDU32:
    case OP_ADDI64:
    case OP_ADDU64:
    case OP_ADDF32:
    case OP_ADDF64:
    case OP_SUBI8:
    case OP_SUBU8:
    case OP_SUBI16:
    case OP_SUBU16:
    case OP_SUBI32:
    case OP_SUBU32:
    case OP_SUBI64:
    case OP_SUBU64:
    case OP_SUBF32:
    case OP_SUBF64:
    case OP_DIVI8:
    case OP_DIVU8:
    case OP_DIVI16:
    case OP_DIVU16:
    case OP_DIVI32:
    case OP_DIVU32:
    case OP_DIVI64:
    case OP_DIVU64:
    case OP_DIVF32:
    case OP_DIVF64:
    case OP_MULI8:
    case OP_MULU8:
    case OP_MULI16:
    case OP_MULU16:
    case OP_MULI32:
    case OP_MULU32:
    case OP_MULI64:
    case OP_MULU64:
    case OP_MULF32:
    case OP_MULF64:
    case OP_MODI8:
    case OP_MODU8:
    case OP_MODI16:
    case OP_MODU16:
    case OP_MODI32:
    case OP_MODU32:
    case OP_MODI64:
    case OP_MODU64:
    case OP_MODF32:
    case OP_MODF64:
    case OP_POWI8:
    case OP_POWU8:
    case OP_POWI16:
    case OP_POWU16:
    case OP_POWI32:
    case OP_POWU32:
    case OP_POWI64:
    case OP_POWU64:
    case OP_POWF32:
    case OP_POWF64:
    case OP_EQ8:
    case OP_EQ16:
    case OP_EQ32:
    case OP_EQ64:
    case OP_EQARR:
    case OP_EQSTRUCT:
    case OP_NEQ8:
    case OP_NEQ16:
    case OP_NEQ32:
    case OP_NEQ64:
    case OP_NEQARR:
    case OP_NEQSTRUCT:
    case OP_GTI8:
    case OP_GTU8:
    case OP_GTI16:
    case OP_GTU16:
    case OP_GTI32:
    case OP_GTU32:
    case OP_GTI64:
    case OP_GTU64:
    case OP_GTF32:
    case OP_GTF64:
    case OP_GTARR:
    case OP_GTEI8:
    case OP_GTEU8:
    case OP_GTEI16:
    case OP_GTEU16:
    case OP_GTEI32:
    case OP_GTEU32:
    case OP_GTEI64:
    case OP_GTEU64:
    case OP_GTEF32:
    case OP_GTEF64:
    case OP_GTEARR:
    case OP_LTI8:
    case OP_LTU8:
    case OP_LTI16:
    case OP_LTU16:
    case OP_LTI32:
    case OP_LTU32:
    case OP_LTI64:
    case OP_LTU64:
    case OP_LTF32:
    case OP_LTF64:
    case OP_LTARR:
    case OP_LTEI8:
    case OP_LTEU8:
    case OP_LTEI16:
    case OP_LTEU16:
    case OP_LTEI32:
    case OP_LTEU32:
    case OP_LTEI64:
    case OP_LTEU64:
    case OP_LTEF32:
    case OP_LTEF64:
    case OP_LTEARR:
      *buf = static_cast<uint8>(va_arg(list, int32));
      *(buf + 1) = static_cast<uint8>(va_arg(list, int32));
      *(buf + 2) = static_cast<uint8>(va_arg(list, int32));
      memset(buf + 3, 0, 6);
      break;
  }
}