
#include "type_conv.h"
  
//
// This file was automatically generated by a deno script in:
// deno-scripts/opcode-gen.ts
//

opcode conversionOpCode(primitivekind from, primitivekind to) {
  switch (from) {
    case PK_INT8:
      switch(to) {
        case PK_UINT8: return OP_I8TU8;
        case PK_INT16: return OP_I8TI16;
        case PK_UINT16: return OP_I8TU16;
        case PK_INT32: return OP_I8TI32;
        case PK_UINT32: return OP_I8TU32;
        case PK_INT64: return OP_I8TI64;
        case PK_UINT64: return OP_I8TU64;
        case PK_FLOAT32: return OP_I8TF32;
        case PK_FLOAT64: return OP_I8TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_BOOL:
    case PK_UINT8:
      switch(to) {
        case PK_INT8: return OP_U8TI8;
        case PK_INT16: return OP_U8TI16;
        case PK_INT32: return OP_U8TI32;
        case PK_INT64: return OP_U8TI64;
        case PK_FLOAT32: return OP_U8TF32;
        case PK_FLOAT64: return OP_U8TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_INT16:
      switch(to) {
        case PK_INT8: return OP_I16TI8;
        case PK_UINT8: return OP_I16TU8;
        case PK_UINT16: return OP_I16TU16;
        case PK_INT32: return OP_I16TI32;
        case PK_UINT32: return OP_I16TU32;
        case PK_INT64: return OP_I16TI64;
        case PK_UINT64: return OP_I16TU64;
        case PK_FLOAT32: return OP_I16TF32;
        case PK_FLOAT64: return OP_I16TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_UINT16:
      switch(to) {
        case PK_INT8: return OP_U16TI8;
        case PK_INT16: return OP_U16TI16;
        case PK_INT32: return OP_U16TI32;
        case PK_INT64: return OP_U16TI64;
        case PK_FLOAT32: return OP_U16TF32;
        case PK_FLOAT64: return OP_U16TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_INT32:
      switch(to) {
        case PK_INT8: return OP_I32TI8;
        case PK_UINT8: return OP_I32TU8;
        case PK_INT16: return OP_I32TI16;
        case PK_UINT16: return OP_I32TU16;
        case PK_UINT32: return OP_I32TU32;
        case PK_INT64: return OP_I32TI64;
        case PK_UINT64: return OP_I32TU64;
        case PK_FLOAT32: return OP_I32TF32;
        case PK_FLOAT64: return OP_I32TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_UINT32:
      switch(to) {
        case PK_INT8: return OP_U32TI8;
        case PK_INT16: return OP_U32TI16;
        case PK_INT32: return OP_U32TI32;
        case PK_INT64: return OP_U32TI64;
        case PK_FLOAT32: return OP_U32TF32;
        case PK_FLOAT64: return OP_U32TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_INT64:
      switch(to) {
        case PK_INT8: return OP_I64TI8;
        case PK_UINT8: return OP_I64TU8;
        case PK_INT16: return OP_I64TI16;
        case PK_UINT16: return OP_I64TU16;
        case PK_INT32: return OP_I64TI32;
        case PK_UINT32: return OP_I64TU32;
        case PK_UINT64: return OP_I64TU64;
        case PK_FLOAT32: return OP_I64TF32;
        case PK_FLOAT64: return OP_I64TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_UINT64:
      switch(to) {
        case PK_INT8: return OP_U64TI8;
        case PK_INT16: return OP_U64TI16;
        case PK_INT32: return OP_U64TI32;
        case PK_INT64: return OP_U64TI64;
        case PK_FLOAT32: return OP_U64TF32;
        case PK_FLOAT64: return OP_U64TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_FLOAT32:
      switch(to) {
        case PK_INT8: return OP_F32TI8;
        case PK_UINT8: return OP_F32TU8;
        case PK_INT16: return OP_F32TI16;
        case PK_UINT16: return OP_F32TU16;
        case PK_INT32: return OP_F32TI32;
        case PK_UINT32: return OP_F32TU32;
        case PK_INT64: return OP_F32TI64;
        case PK_UINT64: return OP_F32TU64;
        case PK_FLOAT64: return OP_F32TF64;
        default: return OP_NOP;
      }
      return OP_NOP;
    case PK_FLOAT64:
      switch(to) {
        case PK_INT8: return OP_F64TI8;
        case PK_UINT8: return OP_F64TU8;
        case PK_INT16: return OP_F64TI16;
        case PK_UINT16: return OP_F64TU16;
        case PK_INT32: return OP_F64TI32;
        case PK_UINT32: return OP_F64TU32;
        case PK_INT64: return OP_F64TI64;
        case PK_UINT64: return OP_F64TU64;
        case PK_FLOAT32: return OP_F64TF32;
        default: return OP_NOP;
      }
      return OP_NOP;
    default: return OP_NOP;
  }
}