#ifndef QUICKSCRIPT_TYPE_CONV_H
#define QUICKSCRIPT_TYPE_CONV_H

//
// This file was automatically generated by a deno script in:
// ./deno-code-gen
//

#include "../interpreter/opcodes.h"
#include "../types/types.h"

opcode conversionOpCode(primitivekind from, primitivekind to);

#endif // QUICKSCRIPT_TYPE_CONV_H