#ifndef OPCODE_PRINTER_H
#define OPCODE_PRINTER_H

#include <cstdio>

#include "qs/interpreter/opcodes.hpp"
#include "qs/types/types.hpp"

//
// This file was automatically generated by a deno script in:
// ./deno-code-gen
//

void printTypeIndex(FILE* out, typeindex idx);

void printInstructionToString(uint8* buf, FILE* out, uint8* strPool);

#endif // OPCODE_PRINTER_H